### ISSUE TITLE
Network Chaos can not be injected into privileged pod

### ISSUE THREAD

**Issue by kateryna-automation-hero** [chaos-mesh/chaos-mesh#1328]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

I installed Chaos Mesh (version v1.0.3) with helm chart (version 0.3.3). 
Created network chaos experiment on the dashboard targeted to set of privileged pods.

Got an error on Dashboard:
```
An error occurred: 1 error occurred: * admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = error code: exit status 101, msg: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EACCES)', src/main.rs:75:61 stack backtrace: 0: backtrace::backtrace::libunwind::trace at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86 1: backtrace::backtrace::trace_unsynchronized at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66 2: std::sys_common::backtrace::_print_fmt at src/libstd/sys_common/backtrace.rs:78 3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt at src/libstd/sys_common/backtrace.rs:59 4: core::fmt::write at src/libcore/fmt/mod.rs:1076 5: std::io::Write::write_fmt at src/libstd/io/mod.rs:1537 6: std::sys_common::backtrace::_print at src/libstd/sys_common/backtrace.rs:62 7: std::sys_common::backtrace::print at src/libstd/sys_common/backtrace.rs:49 8: std::panicking::default_hook::{{closure}} at src/libstd/panicking.rs:198 9: std::panicking::default_hook at src/libstd/panicking.rs:217 10: std::panicking::rust_panic_with_hook at src/libstd/panicking.rs:520 11: rust_begin_unwind at src/libstd/panicking.rs:431 12: core::panicking::panic_fmt at src/libcore/panicking.rs:85 13: core::option::expect_none_failed at src/libcore/option.rs:1269 14: nsexec::main 15: std::rt::lang_start::{{closure}} 16: std::rt::lang_start_internal::{{closure}} at src/libstd/rt.rs:52 17: std::panicking::try::do_call at src/libstd/panicking.rs:342 18: std::panicking::try at src/libstd/panicking.rs:319 19: std::panic::catch_unwind at src/libstd/panic.rs:394 20: std::rt::lang_start_internal at src/libstd/rt.rs:51 21: main 22: __libc_start_main 23: _start note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Logs of chaos daemon:
```
2020-12-23T13:46:29.718+0100	INFO	chaos-daemon-server	flush ipset	{"request": "container_id:\"docker://55ee9d94f5c0801a5c02eda22c7dda4a26b315103e434d3705c59f05036ad132\" "}
2020-12-23T13:46:29.721+0100	INFO	chaos-daemon-server	Set iptables chains	{"request": "container_id:\"docker://55ee9d94f5c0801a5c02eda22c7dda4a26b315103e434d3705c59f05036ad132\" "}
2020-12-23T13:46:29.722+0100	INFO	background-process-manager	build command	{"command": "/usr/local/bin/nsexec -n /proc/25963/ns/net -- iptables -w -N CHAOS-INPUT"}
2020-12-23T13:46:29.750+0100	ERROR	chaos-daemon-server	error while initializing iptables	{"error": "error code: exit status 101, msg: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EACCES)', src/main.rs:75:61\nstack backtrace:\n   0: backtrace::backtrace::libunwind::trace\n             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86\n   1: backtrace::backtrace::trace_unsynchronized\n             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66\n   2: std::sys_common::backtrace::_print_fmt\n             at src/libstd/sys_common/backtrace.rs:78\n   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt\n             at src/libstd/sys_common/backtrace.rs:59\n   4: core::fmt::write\n             at src/libcore/fmt/mod.rs:1076\n   5: std::io::Write::write_fmt\n             at src/libstd/io/mod.rs:1537\n   6: std::sys_common::backtrace::_print\n             at src/libstd/sys_common/backtrace.rs:62\n   7: std::sys_common::backtrace::print\n             at src/libstd/sys_common/backtrace.rs:49\n   8: std::panicking::default_hook::{{closure}}\n             at src/libstd/panicking.rs:198\n   9: std::panicking::default_hook\n             at src/libstd/panicking.rs:217\n  10: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:520\n  11: rust_begin_unwind\n             at src/libstd/panicking.rs:431\n  12: core::panicking::panic_fmt\n             at src/libcore/panicking.rs:85\n  13: core::option::expect_none_failed\n             at src/libcore/option.rs:1269\n  14: nsexec::main\n  15: std::rt::lang_start::{{closure}}\n  16: std::rt::lang_start_internal::{{closure}}\n             at src/libstd/rt.rs:52\n  17: std::panicking::try::do_call\n             at src/libstd/panicking.rs:342\n  18: std::panicking::try\n             at src/libstd/panicking.rs:319\n  19: std::panic::catch_unwind\n             at src/libstd/panic.rs:394\n  20: std::rt::lang_start_internal\n             at src/libstd/rt.rs:51\n  21: main\n  22: __libc_start_main\n  23: _start\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*daemonServer).SetIptablesChains
	/src/pkg/chaosdaemon/iptables_server.go:47
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_SetIptablesChains_Handler.func1
	/src/pkg/chaosdaemon/pb/chaosdaemon.pb.go:1765
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/utils.TimeoutServerInterceptor
	/src/pkg/utils/grpc.go:84
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_SetIptablesChains_Handler
	/src/pkg/chaosdaemon/pb/chaosdaemon.pb.go:1767
google.golang.org/grpc.(*Server).processUnaryRPC
	/root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024
google.golang.org/grpc.(*Server).handleStream
	/root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313
google.golang.org/grpc.(*Server).serveStreams.func1.1
	/root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722
```

**Work around**
Edit chaos daemon set, make it privileged as well.

**Comment by YangKeao** [comment]
I found that the permission check fails in `cap_capable` function:

```c
int cap_capable(const struct cred *cred, struct user_namespace *targ_ns,
		int cap, unsigned int opts)
{
	struct user_namespace *ns = targ_ns;

	/* See if cred has the capability in the target user namespace
	 * by examining the target user namespace and all of the target
	 * user namespace's parents.
	 */
	for (;;) {
		/* Do we have the necessary capabilities? */
		if (ns == cred->user_ns)
			return cap_raised(cred->cap_effective, cap) ? 0 : -EPERM;

		/*
		 * If we're already at a lower level than we're looking for,
		 * we're done searching.
		 */
		if (ns->level <= cred->user_ns->level)
			return -EPERM;

		/* 
		 * The owner of the user namespace in the parent of the
		 * user namespace has all caps.
		 */
		if ((ns->parent == cred->user_ns) && uid_eq(ns->owner, cred->euid))
			return 0;

		/*
		 * If you have a capability in a parent user ns, then you have
		 * it over all children user namespaces as well.
		 */
		ns = ns->parent;
	}

	/* We never get here */
}
```

However, AFAIK, all docker containers share the same user namespace, so I cannot find how the `privileged` of target process affects the capabilities check 🤦 . I will try to trace the parameters and find the reasons.

**Comment by YangKeao** [comment]
I failed to reproduce this problem on my local development environment (Linux 5.4.80) and CentOS 7 (Linux 3.14). @fewdan Can you help me to check on the EKS?

```c
static int proc_ns_readlink(struct dentry *dentry, char __user *buffer, int buflen)
{
	struct inode *inode = d_inode(dentry);
	const struct proc_ns_operations *ns_ops = PROC_I(inode)->ns_ops;
	struct task_struct *task;
	char name[50];
	int res = -EACCES;

	task = get_proc_task(inode);
	if (!task)
		return res;

	if (ptrace_may_access(task, PTRACE_MODE_READ_FSCREDS)) {
		res = ns_get_name(name, sizeof(name), task, ns_ops);
		if (res >= 0)
			res = readlink_copy(buffer, buflen, name);
	}
	put_task_struct(task);
	return res;
}
```

It seems that `CAP_SYS_PTRACE` is enough.

**Comment by fewdan** [comment]
`
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:31:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
`

I tested it on eks and I am sorry that I did not reproduce this problem.

**Comment by kateryna-automation-hero** [comment]
Our nodes of AWS EKS cluster had Ubuntu1804 OS. Now we migrated to Amazon Linux 2 and there is no more issues with Network Chaos.
