### ISSUE TITLE
controller-manager will be panic if chaos experiment with unexpected phase

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#1568]
## Bug Report

**What version of Chaos Mesh are you using?**

v1.1.0

**What did you do?**

update the phase of chaos experiment to `paused`, which is unexpected, should be `Paused`

can see the slack message https://cloud-native.slack.com/archives/C0193VAV272/p1615403884032700

**What did you expect to see?**
controller-manager just print some error log.

**What did you see instead?**
controller-manager's status change to CrashLoopBackOff, and can get the panic log:

```log
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14075a5]

goroutine 551 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x15c1080, 0x25aa080)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*chaosStateMachine).run(0xc0008b9040, 0x19fc260, 0xc0008b8f80, 0x17a01ea, 0x8, 0xc00ab82cf3cf5381, 0xcc5c61c, 0x25cbaa0, 0xc0008b9040, 0x40, ...)
        /mnt/controllers/twophase/state_machine.go:188 +0x225
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*chaosStateMachine).Into(0xc0008b9040, 0x19fc260, 0xc0008b8f80, 0x17a01ea, 0x8, 0xc00ab82cf3cf5381, 0xcc5c61c, 0x25cbaa0, 0xc0001d9400, 0x0)
        /mnt/controllers/twophase/state_machine.go:192 +0x9e
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile(0xc000190dc0, 0xc000435239, 0x7, 0xc000174690, 0x23, 0xc0008b8f00, 0x0, 0x0, 0x0)
        /mnt/controllers/twophase/types.go:101 +0x798
github.com/chaos-mesh/chaos-mesh/pkg/router.(*Reconciler).Reconcile(0xc0006fdd40, 0xc000435239, 0x7, 0xc000174690, 0x23, 0x0, 0xc00ab82cf3cf117d, 0xc0001c2360, 0xc000644368)
        /mnt/pkg/router/reconciler.go:109 +0x883
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00045cf00, 0x161b120, 0xc0001859e0, 0x0)
        /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00045cf00, 0xc000582e00)
```

**Comment by cwen0** [comment]
This issue has been fixed in #1569.
