### ISSUE TITLE
[CRI-O NetwokChaos] error while initializing iptables

### ISSUE THREAD

**Issue by Harmattan322** [chaos-mesh/chaos-mesh#2108]
## Bug Report

**What version of Kubernetes are you using?**
**What version of Chaos Mesh are you using?**
**What did you do?**
Same (my other issue with absolutely same infrastructure - https://github.com/chaos-mesh/chaos-mesh/issues/2048)

**What did you expect to see?**
Like this pod-fail, but network tests.
![telegram-cloud-photo-size-2-5388808467889894452-y](https://user-images.githubusercontent.com/19413892/125287919-32793a00-e326-11eb-8d22-0dc7c96b54bd.jpg)

**What did you see instead?**

![telegram-cloud-photo-size-2-5431345793924707446-y](https://user-images.githubusercontent.com/19413892/125287821-11b0e480-e326-11eb-9483-71bcfde7f0ca.jpg)

logs on daemon pod's node:

```
2021-07-12T11:45:17.140+0300   ERROR   chaos-daemon-server    Failed to retrieve the cgroup path    {"subsystem": "hugetlb", "target": "b2ce724415e06559b0d7ce9961266289d170f3627392b1a616a0e970753aed1c", "error": "parse cgroup file /proc/2227585/cgroup: open /proc/2227585/cgroup: no such file or directory", "errorVerbose": "open /proc/2227585/cgroup: no such file or directory\nparse cgroup file /proc/2227585/cgroup\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.pidPath\n\t/mnt/pkg/chaosdaemon/stress_server_linux.go:164\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).ExecStressors\n\t/mnt/pkg/chaosdaemon/stress_server_linux.go:51\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ExecStressors_Handler.func1\n\t/mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:2025\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25\ngithub.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor\n\t/mnt/pkg/grpc/utils.go:108\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ExecStressors_Handler\n\t/mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:2027\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}
github.com/go-logr/zapr.(*zapLogger).Error
        /tmp/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.findValidCgroup
        /mnt/pkg/chaosdaemon/stress_server_linux.go:145
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).ExecStressors
        /mnt/pkg/chaosdaemon/stress_server_linux.go:56
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ExecStressors_Handler.func1
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:2025
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
        /mnt/pkg/grpc/utils.go:108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ExecStressors_Handler
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:2027
google.golang.org/grpc.(*Server).processUnaryRPC
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024
google.golang.org/grpc.(*Server).handleStream
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313
google.golang.org/grpc.(*Server).serveStreams.func1.1
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722


... (spam for all cgroups like StressChaos - https://github.com/chaos-mesh/chaos-mesh/issues/2048) ...


2021-07-12T14:49:13.738+0300   INFO    chaos-daemon-server    flush ipset    {"request": "container_id:\"cri-o://b2ce724415e06559b0d7ce9961266289d170f3627392b1a616a0e970753aed1c\" enterNS:true "}
2021-07-12T14:49:13.804+0300   INFO    chaos-daemon-server    Set iptables chains        {"request": "container_id:\"cri-o://b2ce724415e06559b0d7ce9961266289d170f3627392b1a616a0e970753aed1c\" enterNS:true "}
2021-07-12T14:49:13.806+0300   INFO    background-process-manager     build command        {"command": "/usr/local/bin/nsexec -n /proc/2227585/ns/net -- iptables -w -N CHAOS-INPUT"}
2021-07-12T14:49:15.903+0300   ERROR   chaos-daemon-server    error while initializing iptables       {"error": "error code: exit status 101, msg: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(ENOENT)', src/main.rs:75:61\nstack backtrace:\n   0: backtrace::backtrace::libunwind::trace\n             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86\n   1: backtrace::backtrace::trace_unsynchronized\n             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66\n   2: std::sys_common::backtrace::_print_fmt\n             at src/libstd/sys_common/backtrace.rs:78\n   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt\n             at src/libstd/sys_common/backtrace.rs:59\n   4: core::fmt::write\n             at src/libcore/fmt/mod.rs:1076\n   5: std::io::Write::write_fmt\n             at src/libstd/io/mod.rs:1537\n   6: std::sys_common::backtrace::_print\n             at src/libstd/sys_common/backtrace.rs:62\n   7: std::sys_common::backtrace::print\n             at src/libstd/sys_common/backtrace.rs:49\n   8: std::panicking::default_hook::{{closure}}\n             at src/libstd/panicking.rs:198\n   9: std::panicking::default_hook\n             at src/libstd/panicking.rs:217\n  10: std::panicking::rust_panic_with_hook\n             at src/libstd/panicking.rs:520\n  11: rust_begin_unwind\n             at src/libstd/panicking.rs:431\n  12: core::panicking::panic_fmt\n             at src/libcore/panicking.rs:85\n  13: core::option::expect_none_failed\n             at src/libcore/option.rs:1269\n  14: nsexec::main\n  15: std::rt::lang_start::{{closure}}\n  16: std::rt::lang_start_internal::{{closure}}\n             at src/libstd/rt.rs:52\n  17: std::panicking::try::do_call\n             at src/libstd/panicking.rs:342\n  18: std::panicking::try\n             at src/libstd/panicking.rs:319\n  19: std::panic::catch_unwind\n             at src/libstd/panic.rs:394\n  20: std::rt::lang_start_internal\n             at src/libstd/rt.rs:51\n  21: main\n  22: __libc_start_main\n  23: _start\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"}
github.com/go-logr/zapr.(*zapLogger).Error
        /tmp/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).SetIptablesChains
        /mnt/pkg/chaosdaemon/iptables_server.go:45
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_SetIptablesChains_Handler.func1
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:1935
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
        /mnt/pkg/grpc/utils.go:108
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_SetIptablesChains_Handler
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:1937
google.golang.org/grpc.(*Server).processUnaryRPC
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024
google.golang.org/grpc.(*Server).handleStream
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313
google.golang.org/grpc.(*Server).serveStreams.func1.1
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722
```

**Output of chaosctl**
No way to use in my internal private network

**Comment by Harmattan322** [comment]
Found one more detail:
![telegram-cloud-photo-size-2-5438477423910957879-y](https://user-images.githubusercontent.com/19413892/125598865-f12a1ddd-b66b-4047-9761-38f5f776583c.jpg)
By the way logs of one of the demons:
![telegram-cloud-document-2-5438477423454719325](https://user-images.githubusercontent.com/19413892/125598913-662487d9-682b-4533-b85a-480be8c8f430.jpg)
Any suggestions, how do I fix these alerts in openshift cluster?

**Comment by YangKeao** [comment]
> Found one more detail:
> ![telegram-cloud-photo-size-2-5438477423910957879-y](https://user-images.githubusercontent.com/19413892/125598865-f12a1ddd-b66b-4047-9761-38f5f776583c.jpg)
> By the way logs of one of the demons:
> ![telegram-cloud-document-2-5438477423454719325](https://user-images.githubusercontent.com/19413892/125598913-662487d9-682b-4533-b85a-480be8c8f430.jpg)
> Any suggestions, how do I fix these alerts in openshift cluster?

`chaos-daemon` uses 31767 and 31766 ports by default. If these ports are already used on your server, you could install chaos mesh with helm configuration `--set chaosDaemon.httpPort=xxxxx --set chaosDaemon.grpcPort=xxxxx` to use another port.

**Comment by Harmattan322** [comment]
@YangKeao, has been used another (free) ports - no alerts in Daemon Set , but error is the same.
![image](https://user-images.githubusercontent.com/19413892/126463886-36edf593-1665-4d3f-9aa7-8510902c9742.png)
