### ISSUE TITLE
chaosctl debug iochaos failed

### ISSUE THREAD

**Issue by iguoyr** [chaos-mesh/chaos-mesh#2313]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

**What did you do?**

As the https://github.com/chaos-mesh/chaos-mesh/issues/2305 reported, `chaosctl debug iochaos` cannot work.

**What did you expect to see?**
`chaosctl debug iochaos` can print the right result. 

**What did you see instead?**
output of `./chaosctl debug iochaos -n chaos-testing`:

```
I0915 12:51:23.346253   74236 request.go:668] Waited for 1.000311534s due to client-side throttling, not priority and fairness, request: GET:https://c100-e.us-east.containers.cloud.ibm.com:32691/apis/autoscaling/v1?timeout=32s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x25940a5]

goroutine 1 [running]:
github.com/chaos-mesh/chaos-mesh/api/v1alpha1.(*ChaosKind).SpawnList(...)
	/Users/faraktingi/Documents/_travail/github/chaos-mesh/api/v1alpha1/kinds.go:77
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/common.GetChaosList(0x2c9adf8, 0xc00053ae40, 0xc000a8f179, 0x7, 0x0, 0x0, 0x7ffeefbffae4, 0xd, 0x2cb2bd8, 0xc00042c000, ...)
	/Users/faraktingi/Documents/_travail/github/chaos-mesh/pkg/chaosctl/common/common.go:220 +0xc5
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/cmd.(*DebugOptions).Run(0xc00038a6c0, 0x2a0ae05, 0x7, 0xc0002ef7c0, 0x0, 0x2, 0xc000d94078, 0x0, 0x0)
	/Users/faraktingi/Documents/_travail/github/chaos-mesh/pkg/chaosctl/cmd/debug.go:178 +0x13b
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/cmd.NewDebugCommand.func5(0xc0004b5b80, 0xc0002ef7c0, 0x0, 0x2, 0x0, 0x0)
	/Users/faraktingi/Documents/_travail/github/chaos-mesh/pkg/chaosctl/cmd/debug.go:129 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc0004b5b80, 0xc0002ef7a0, 0x2, 0x2, 0xc0004b5b80, 0xc0002ef7a0)
	/Users/faraktingi/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x398af60, 0xc000713ec8, 0x1, 0x1)
	/Users/faraktingi/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/faraktingi/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/cmd.Execute()
	/Users/faraktingi/Documents/_travail/github/chaos-mesh/pkg/chaosctl/cmd/root.go:78 +0x675
main.main()
	/Users/faraktingi/Documents/_travail/github/chaos-mesh/cmd/chaosctl/main.go:19 +0x25
```
**Output of chaosctl**

**Comment by Hexilee** [comment]
Hi, we are refactoring chaosctl in #2243, this issue will be outdated.
