### ISSUE TITLE
failed to create a exam by yaml! thanks

### ISSUE THREAD

**Issue by pengliangyou** [chaos-mesh/chaos-mesh#2677]
## Bug Report

**What version of Kubernetes are you using?**
minikube

**What version of Chaos Mesh are you using?**
latest

**What did you do?**
i create a examination by yaml and get a "white page"
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'categories')
    at uo (Step1.tsx:187:39)
    at ia (react-dom.production.min.js:157:137)
    at Hs (react-dom.production.min.js:267:460)
    at Cc (react-dom.production.min.js:250:347)
    at Sc (react-dom.production.min.js:250:278)
    at kc (react-dom.production.min.js:250:138)
    at vc (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vi (react-dom.production.min.js:122:325)
<img width="785" alt="image" src="https://user-images.githubusercontent.com/65885838/146739530-b4cf514a-e7f8-4a72-9145-20f764d12124.png">
<img width="576" alt="image" src="https://user-images.githubusercontent.com/65885838/146739691-55962d37-b492-40e2-9e4c-aaed903b5c5b.png">

**Comment by YangKeao** [comment]
@g1eny0ung PTAL

**Comment by angoothachap** [comment]
I'm getting this error when I query` /experiments/experimentID `also

**Comment by imlonghao** [comment]
I am also having the same issue during `load` and `import` a StressChaos.

**Comment by boxker** [comment]
Hi, is there any progress on this issue?
