### ISSUE TITLE
target process 3548713 doesn't respond within 10500ms or HotSpot VM not loaded

### ISSUE THREAD

**Issue by jiangyingforSH** [chaos-mesh/chaos-mesh#2744]
/usr/local/byteman/lib/byteman-install.jar
java  -classpath /usr/local/byteman/lib/byteman-install.jar org.jboss.byteman.agent.install.Install -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 3548713
install com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/3548713/root/tmp/.java_pid1: target process 3548713 doesn't respond within 10500ms or HotSpot VM not loaded
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/3548713/root/tmp/.java_pid1: target process 3548713 doesn't respond within 10500ms or HotSpot VM not loaded
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at org.jboss.byteman.agent.install.Install.attach(Install.java:452)
	at org.jboss.byteman.agent.install.Install.main(Install.java:60)
	{"error": "exit status 1"}

**Comment by WangXiangUSTC** [comment]
system info:

Linux version 4.19.91-23.al7.x86_64 (mockbuild@koji.alibaba-inc.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)) #1 SMP Tue Mar 23 18:02:34 CST 2021

**Comment by STRRL** [comment]
The reason of this issue might be PID of `java` is not 1
