### ISSUE TITLE
Some error occur, rpc error: code = Unknown desc = exit status 1

### ISSUE THREAD

**Issue by rongGreate** [chaos-mesh/chaos-mesh#3061]
What version of Kubernetes are you using?

v1.22.3

What version of Chaos Mesh are you using?

v2.1.3

What did you do?

create JVM experiments

What did you expect to see?

experiments can work

What did you see instead?

![image](https://user-images.githubusercontent.com/94539012/160077301-3a7acc18-b88f-4561-ba2a-a91008919c13.png)

here is the experiment info:

```
kind: JVMChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: test
  name: shop-order-notify-exception
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - test
    labelSelectors:
      statefulset.kubernetes.io/pod-name: saas-test-shop-order-cny-0
  mode: all
  action: exception
  name: shop-order-notify-exception
  class: com.opay.saas.order.api.controller.CustomerOrderManagerController
  method: notify
  value: ''
  exception: java.lang.RuntimeException
  latency: 0
  cpuCount: 0
  memType: ''
  port: 9283
  ruleData: ''
```

i find chaos-controller-manager some logs :

```
2022-03-25T07:37:52.570Z	ERROR	jvmchaos	jvmchaos/impl.go:138	uninstall jvm rules	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/jvmchaos.(*Impl).Recover
	/mnt/controllers/chaosimpl/jvmchaos/impl.go:138
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:172
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:37:52.570Z	ERROR	records	records/controller.go:179	fail to recover chaos	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:179
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:37:52.570Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":true,"RequeueAfter":0}}
2022-03-25T07:39:25.115Z	INFO	setup	logr@v1.2.0/logr.go:249	watcher channel has closed, restart watcher
2022-03-25T07:39:27.116Z	INFO	setup	logr@v1.2.0/logr.go:249	Launching watcher for ConfigMaps
2022-03-25T07:39:27.116Z	INFO	inject-webhook	logr@v1.2.0/logr.go:249	Watching for ConfigMaps for changes	{"template namespace": "chaos-testing", "labels": {"app.kubernetes.io/component":"webhook"}}
2022-03-25T07:48:47.931Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2022-03-25T07:48:47.931Z	INFO	desiredphase	desiredphase/controller.go:130	modify desiredPhase	{"desiredPhase": "Stop"}
2022-03-25T07:48:47.931Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2022-03-25T07:48:47.931Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2022-03-25T07:48:47.931Z	INFO	records	records/controller.go:117	iterating record	{"record": {"id":"test/saas-test-shop-order-cny-0/saas-shop-order-cny","selectorKey":".","phase":"Injected"}, "desiredPhase": "Stop"}
2022-03-25T07:48:47.931Z	INFO	records	records/controller.go:171	recover chaos	{"id": "test/saas-test-shop-order-cny-0/saas-shop-order-cny"}
2022-03-25T07:48:47.931Z	INFO	controller-chaos-daemon-client-utils	logr@v1.2.0/logr.go:249	Creating client to chaos-daemon	{"node": "cn-hangzhou.192.168.212.117"}
2022-03-25T07:48:48.043Z	ERROR	jvmchaos	jvmchaos/impl.go:138	uninstall jvm rules	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/jvmchaos.(*Impl).Recover
	/mnt/controllers/chaosimpl/jvmchaos/impl.go:138
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:172
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:48:48.043Z	ERROR	records	records/controller.go:179	fail to recover chaos	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:179
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:48:48.043Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":true,"RequeueAfter":0}}
```

i dont know how to solve it

**Comment by rongGreate** [comment]
`
2022-03-25T07:37:52.570Z ERROR jvmchaos jvmchaos/impl.go:138 uninstall jvm rules {"error": "rpc error: code = Unknown desc = exit status 1"} github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/jvmchaos.(*Impl).Recover /mnt/controllers/chaosimpl/jvmchaos/impl.go:138 github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile /mnt/controllers/common/records/controller.go:172 github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile /mnt/controllers/common/pipeline/pipeline.go:73 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2 /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
`

**Comment by rongGreate** [comment]
```kubectl logs chaos-controller-manager-6f488d7598-69b7h -n chaos-testing

**Comment by rongGreate** [comment]
```
2022-03-25T07:37:52.570Z	ERROR	jvmchaos	jvmchaos/impl.go:138	uninstall jvm rules	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/jvmchaos.(*Impl).Recover
	/mnt/controllers/chaosimpl/jvmchaos/impl.go:138
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:172
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:37:52.570Z	ERROR	records	records/controller.go:179	fail to recover chaos	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:179
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:37:52.570Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":true,"RequeueAfter":0}}
2022-03-25T07:39:25.115Z	INFO	setup	logr@v1.2.0/logr.go:249	watcher channel has closed, restart watcher
2022-03-25T07:39:27.116Z	INFO	setup	logr@v1.2.0/logr.go:249	Launching watcher for ConfigMaps
2022-03-25T07:39:27.116Z	INFO	inject-webhook	logr@v1.2.0/logr.go:249	Watching for ConfigMaps for changes	{"template namespace": "chaos-testing", "labels": {"app.kubernetes.io/component":"webhook"}}
2022-03-25T07:48:47.931Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2022-03-25T07:48:47.931Z	INFO	desiredphase	desiredphase/controller.go:130	modify desiredPhase	{"desiredPhase": "Stop"}
2022-03-25T07:48:47.931Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2022-03-25T07:48:47.931Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2022-03-25T07:48:47.931Z	INFO	records	records/controller.go:117	iterating record	{"record": {"id":"test/saas-test-shop-order-cny-0/saas-shop-order-cny","selectorKey":".","phase":"Injected"}, "desiredPhase": "Stop"}
2022-03-25T07:48:47.931Z	INFO	records	records/controller.go:171	recover chaos	{"id": "test/saas-test-shop-order-cny-0/saas-shop-order-cny"}
2022-03-25T07:48:47.931Z	INFO	controller-chaos-daemon-client-utils	logr@v1.2.0/logr.go:249	Creating client to chaos-daemon	{"node": "cn-hangzhou.192.168.212.117"}
2022-03-25T07:48:48.043Z	ERROR	jvmchaos	jvmchaos/impl.go:138	uninstall jvm rules	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/chaosimpl/jvmchaos.(*Impl).Recover
	/mnt/controllers/chaosimpl/jvmchaos/impl.go:138
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:172
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:48:48.043Z	ERROR	records	records/controller.go:179	fail to recover chaos	{"error": "rpc error: code = Unknown desc = exit status 1"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/mnt/controllers/common/records/controller.go:179
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
2022-03-25T07:48:48.043Z	INFO	pipeline	pipeline/pipeline.go:78	reconcile result	{"result": {"Requeue":true,"RequeueAfter":0}}
```

**Comment by rongGreate** [comment]
somebody help me ~

**Comment by Andrewmatilde** [comment]
PTAL , @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
Could you please check the log of `chaos-daemon`, there may be some useful information.

**Comment by rongGreate** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/94539012/160550116-cd6ef0d1-5bf6-49db-b02d-ab158743d397.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/94539012/160550169-4928e72b-46c5-4be8-8fa3-93108f7984f3.png">

**Comment by rongGreate** [comment]
> Could you please check the log of `chaos-daemon`, there may be some useful information.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/94539012/160550116-cd6ef0d1-5bf6-49db-b02d-ab158743d397.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/94539012/160550169-4928e72b-46c5-4be8-8fa3-93108f7984f3.png">

**Comment by rongGreate** [comment]
> Could you please check the log of `chaos-daemon`, there may be some useful information.

sorry, i dont know which one, so i check all of them, but i found that the log seems look the same

**Comment by WangXiangUSTC** [comment]
> > Could you please check the log of `chaos-daemon`, there may be some useful information.
> 
> sorry, i dont know which one, so i check all of them, but i found that the log seems look the same

check the chaos-daemon on node `cn-hangzhou.192.168.212.117`, and search `exit status 1` in it's log @rongGreate

**Comment by rongGreate** [comment]
> > > Could you please check the log of `chaos-daemon`, there may be some useful information.
> > 
> > 
> > sorry, i dont know which one, so i check all of them, but i found that the log seems look the same
> 
> check the chaos-daemon on node `cn-hangzhou.192.168.212.117`, and search `exit status 1` in it's log @rongGreate

i found this below:

```
2022-03-29T06:44:38.701Z	INFO	chaos-daemon.daemon-server	chaosdaemon/jvm_server.go:103	exec comamnd	{"namespacedName": "test/shop-order-notify-exceptionk", "cmd": "/bin/sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 3832840", "output": "-b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 3832840\n\n/usr/local/byteman/lib/byteman-install.jar\njava  -classpath /usr/local/byteman/lib/byteman-install.jar org.jboss.byteman.agent.install.Install -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 3832840\ninstall com.sun.tools.attach.AgentLoadException: 102\ncom.sun.tools.attach.AgentLoadException: 102\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)\n\tat org.jboss.byteman.agent.install.Install.injectAgent(Install.java:525)\n\tat org.jboss.byteman.agent.install.Install.main(Install.java:61)\n", "error": "exit status 1"}
2022-03-29T06:44:38.701Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	bpm/build_linux.go:60	build command	{"namespacedName": "test/shop-order-notify-exceptionk", "command": "/usr/local/bin/nsexec -n /proc/3832840/ns/net -- sh -c bmsubmit.sh -p 9277 -l /tmp/rule.btm3873190496"}
2022-03-29T06:44:38.837Z	ERROR	chaos-daemon.daemon-server	chaosdaemon/jvm_server.go:119	Failed to process request: java.lang.Exception: The remote byteman agent reported an error:
EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:157)
at org.jboss.byteman.agent.TransformListener.handleScripts(TransformListener.java:351)
at org.jboss.byteman.agent.TransformListener.loadScripts(TransformListener.java:274)
at org.jboss.byteman.agent.TransformListener.handleConnection(TransformListener.java:226)
at org.jboss.byteman.agent.TransformListener.run(TransformListener.java:156)

The full response received from the byteman agent follows:
redefine rule shop-order-notify-exceptionk
EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:157)
at org.jboss.byteman.agent.TransformListener.handleScripts(TransformListener.java:351)
at org.jboss.byteman.agent.TransformListener.loadScripts(TransformListener.java:274)
at org.jboss.byteman.agent.TransformListener.handleConnection(TransformListener.java:226)
at org.jboss.byteman.agent.TransformListener.run(TransformListener.java:156)

-- Args were: [/tmp/rule.btm3873190496]
java.lang.Exception: The remote byteman agent reported an error:
EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:157)
at org.jboss.byteman.agent.TransformListener.handleScripts(TransformListener.java:351)
at org.jboss.byteman.agent.TransformListener.loadScripts(TransformListener.java:274)
at org.jboss.byteman.agent.TransformListener.handleConnection(TransformListener.java:226)
at org.jboss.byteman.agent.TransformListener.run(TransformListener.java:156)

The full response received from the byteman agent follows:
redefine rule shop-order-notify-exceptionk
EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
at org.jboss.byteman.agent.Retransformer.installScript(Retransformer.java:157)
at org.jboss.byteman.agent.TransformListener.handleScripts(TransformListener.java:351)
at org.jboss.byteman.agent.TransformListener.loadScripts(TransformListener.java:274)
at org.jboss.byteman.agent.TransformListener.handleConnection(TransformListener.java:226)
at org.jboss.byteman.agent.TransformListener.run(TransformListener.java:156)

	at org.jboss.byteman.agent.submit.Submit$Comm.readResponse(Submit.java:966)
	at org.jboss.byteman.agent.submit.Submit.submitRequest(Submit.java:790)
	at org.jboss.byteman.agent.submit.Submit.addScripts(Submit.java:603)
	at org.jboss.byteman.agent.submit.Submit.addRulesFromFiles(Submit.java:555)
	at org.jboss.byteman.agent.submit.Submit.main(Submit.java:1147)
	{"namespacedName": "test/shop-order-notify-exceptionk", "error": "exit status 1"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).InstallJVMRules
	/mnt/pkg/chaosdaemon/jvm_server.go:119
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler.func1
	/mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3655
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1
	/mnt/pkg/chaosdaemon/server.go:176
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
	/mnt/pkg/grpc/utils.go:205
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler
	/mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3657
google.golang.org/grpc.(*Server).processUnaryRPC
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297
google.golang.org/grpc.(*Server).handleStream
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941
```

**Comment by rongGreate** [comment]
> 

```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```

**Comment by rongGreate** [comment]
> OK, the key message is `EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)`, I will take a look.
> 
> By the way, could you please provide the java version?

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

thanks your reply

**Comment by rongGreate** [comment]
> 

my friend,  waiting your reply

**Comment by rongGreate** [comment]
> OK, the key message is `EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)`, I will take a look.
> 
> By the way, could you please provide the java version?

**Comment by rongGreate** [comment]
> OK, the key message is `EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)`, I will take a look.
> 
> By the way, could you please provide the java version?

PTAL

**Comment by WangXiangUSTC** [comment]
I see `EXCEPTION java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)` is a common error, I search it on Google, one reason may be that another agent has injected the java process, could you please check it?

And I found a little problem in your YMAL file, the exception should be something like `java.lang.RuntimeException("BOOM")`, but it has no relationship with this issue.

**Comment by rongGreate** [comment]
> 

OK,  let me check it,  on the log maybe i found the wrong log
