### ISSUE TITLE
GitHub Action: failed to build chaos-kernel

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3075]
## Bug Report

```
#24 75.87 -- Installing: /bpfki/build/protobuf/lib/cmake/protobuf/protobuf-module.cmake
#24 75.88 [ 36%] Completed 'protobuf'
#24 75.89 [ 36%] Built target protobuf
#24 75.89 Makefile:90: recipe for target 'all' failed
#24 75.89 make: *** [all] Error 2
------
executor failed running [/bin/sh -c cmake .. && make -j${MAKE_JOBS} && mv bin/bpfki /usr/local/bin/ && mv examples/fail* /usr/local/bin/]: exit code: 2
Traceback (most recent call last):
  File "/Users/cwenyin/dev/go/src/github.com/chaos-mesh/chaos-mesh/build/build_image.py", line 169, in <module>
    main()
  File "/Users/cwenyin/dev/go/src/github.com/chaos-mesh/chaos-mesh/build/build_image.py", line 165, in main
    subprocess.run(cmd, env=env, check=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'build', '--build-arg', 'GOPROXY=https://proxy.golang.org,direct', '--build-arg', "LDFLAGS=-s -w -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.buildDate=2022-03-30T03:02:25Z' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitCommit=a2c627eb2d5b4801020220186a3cf1c8438f233e' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitVersion=master-ga2c627eb2d5b48'", '--build-arg', 'GO_BUILD_CACHE=/Users/cwenyin/dev/go/src/github.com/chaos-mesh/chaos-mesh/.cache/chaos-mesh', '--build-arg', 'YARN_BUILD_CACHE=/Users/cwenyin/dev/go/src/github.com/chaos-mesh/chaos-mesh/.cache/yarn', '--build-arg', 'TARGET_PLATFORM=arm64', '-t', 'ghcr.io/pingcap/chaos-kernel:latest', 'images/chaos-kernel']' returned non-zero exit status 1.
make: *** [images/chaos-kernel/.dockerbuilt] Error 1
``` 

Github action log: https://github.com/chaos-mesh/chaos-mesh/runs/5747522180?check_suite_focus=true

**Comment by cwen0** [comment]
```
#24 0.904 CMake Error at zlib-stamp/download-zlib.cmake:170 (message):
#24 0.904   Each download failed!
#24 0.904 
#24 0.904     error: downloading 'https://zlib.net/zlib-1.2.11.tar.gz' failed
#24 0.904           status_code: 22
#24 0.904           status_string: "HTTP response code said error"
#24 0.904           log:
#24 0.904           --- LOG BEGIN ---
#24 0.904             Trying 85.187.148.2:443...
#24 0.904 
#24 0.904   Connected to zlib.net (85.187.148.2) port 443 (#0)
```

**Comment by cwen0** [comment]
This issue has been fixed in https://github.com/chaos-mesh/bpfki/pull/1
