### ISSUE TITLE
AttachNotSupportedException! JVM Chaos Injection failed.

### ISSUE THREAD

**Issue by ywq20011** [chaos-mesh/chaos-mesh#3330]
## Bug Report

**What version of Kubernetes are you using?**
1.20.4

**What version of Chaos Mesh are you using?**
v2.2.0

**What did you do?**

inject JVMChaose:

```
kind: JVMChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: pt-shared-services
  name: memory-stress-uc-1
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  selector:
    namespaces:
      - pt-shared-services
    labelSelectors:
      app: uc-grpc
  mode: all
  action: stress
  port: 9277
  memType: heap
  name: '--stress-1654584195'
  value: ''
  exception: ''
  latency: 0
  ruleData: ''
```

**What did you expect to see?**

inject successfully.

**What did you see instead?**
injection failed.

error log:

2022-06-07T06:57:50.175Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:3926	build command	{"namespacedName": "pt-shared-services/memory-stress-uc", "command": "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compileToBytecode -p 9277 3500466"}
2022-06-07T06:58:11.526Z	ERROR	chaos-daemon.daemon-server	chaosdaemon/server.go:187	com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/3500466/root/tmp/.java_pid3500466: target process 3500466 doesn't respond within 10500ms or HotSpot VM not loaded
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/3500466/root/tmp/.java_pid3500466: target process 3500466 doesn't respond within 10500ms or HotSpot VM not loaded
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at org.chaos_mesh.agent_installer.Install.attach(Install.java:203)
	at org.chaos_mesh.agent_installer.Install.main(Install.java:47)
	{"namespacedName": "pt-shared-services/memory-stress-uc", "error": "exit status 1"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/server.go:187
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/grpc/utils.go:205
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3928
google.golang.org/grpc.(*Server).processUnaryRPC
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297
google.golang.org/grpc.(*Server).handleStream
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941

other informations:

1.  pid 3500466 is the correct java process id.
2. -XX:+StartAttachListener  has been added .
3.
![image](https://user-images.githubusercontent.com/18238676/172357476-b9d012e3-97c7-4055-aa6f-e8a3b2dd30a4.png)

go into chaos deamon pod，we found that the two proc id is not match , this may be the problem?

**Comment by iguoyr** [comment]
Hi @ywq20011, it seems this issue #2751 solved this problem, but the pr #2904 did not merge into v2.1.5, maybe we will cherry pick it into v2.1.x (in the next bugfix version). And v2.2.0 is already released, I think upgrade to v2.2.0 could solve this problem.

**Comment by ywq20011** [comment]
Hi, @iguoyr , we are using v2.2.0.

Maybe this issue is not related to #2751 
pid200534 and pid12 are the same pid.
200534 is the pid on host machine.
12 is then pid in container.

**Comment by WangXiangUSTC** [comment]
It seems that it is similar to https://github.com/chaos-mesh/chaos-mesh/issues/2588

Can you check the Linux kernel's version of the K8s's node? It requires v4.2 at least

**Comment by oldthreefeng** [comment]
so, the requirement should be added  in docs...

**Comment by STRRL** [comment]
> so, the requirement should be added in docs...

Would you like to help us update that? :heart:

**Comment by WangXiangUSTC** [comment]
> 

https://chaos-mesh.org/docs/simulate-jvm-application-chaos/

There is a note in this document, PTAL

**Comment by iguoyr** [comment]
@WangXiangUSTC the document requires v4.1 or later, do we need to update it to v4.2?

**Comment by WangXiangUSTC** [comment]
> It seems that it is similar to #2588
> 
> Can you check the Linux kernel's version of the K8s's node? It requires v4.2 at least

I made a mistake here, 4.1 is OK

**Comment by ywq20011** [comment]
> > It seems that it is similar to #2588
> > Can you check the Linux kernel's version of the K8s's node? It requires v4.2 at least
> 
> I made a mistake here, 4.1 is OK

We update the Linux kernel's version to v5.10 .

unfortunatlly,  a different error happened:

```
Failed to apply chaos: rpc error: code = Unknown desc = com.sun.tools.attach.AgentLoadException: 102
 com.sun.tools.attach.AgentLoadException: 100 at
 jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108) at
jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119) at
jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147) at
jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538) at
org.chaos_mesh.agent_installer.Install.injectAgent(Install.java:255) at
org.chaos_mesh.agent_installer.Install.main(Install.java:48) :
 exit status 1
```

does it have  to be v4.1?

**Comment by WangXiangUSTC** [comment]
Seems that this issue is similar to https://github.com/chaos-mesh/chaos-mesh/issues/2690, and this error should be ignored.

Could you please provide the related error log in chaos-daemon?

**Comment by ywq20011** [comment]
> Seems that this issue is similar to #2690, and this error should be ignored.
> 
> Could you please provide the related error log in chaos-daemon?

We change the kernel's version to v4.19.  

```
2022-06-10T03:12:10.049Z	INFO	chaos-daemon.daemon-server	util/util.go:112	get flatTree	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "source": 90285, "flatTree": []}
2022-06-10T03:12:10.049Z	INFO	chaos-daemon.daemon-server	chaosdaemon/jvm_server.go:50	get flatTree	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "source": 90267, "flatTree": [90285]}
2022-06-10T03:12:10.049Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:3926	build command	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "command": "/usr/local/bin/nsexec -m /proc/90285/ns/mnt -- sh -c mkdir -p /usr/local/byteman/lib/"}
2022-06-10T03:12:10.052Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	chaosdaemon/jvm_server.go:83	build command	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "command": "/usr/local/bin/nsexec -m /proc/90285/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman.jar"}
2022-06-10T03:12:10.055Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	chaosdaemon/jvm_server.go:88	build command	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "command": "/usr/local/bin/nsexec -m /proc/90285/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman-helper.jar"}
2022-06-10T03:12:10.059Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:3926	build command	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "command": "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compileToBytecode -p 9277 90285"}
2022-06-10T03:12:10.436Z	ERROR	chaos-daemon.daemon-server	chaosdaemon/server.go:187	com.sun.tools.attach.AgentLoadException: 102
com.sun.tools.attach.AgentLoadException: 100
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
	at org.chaos_mesh.agent_installer.Install.injectAgent(Install.java:255)
	at org.chaos_mesh.agent_installer.Install.main(Install.java:48)
	{"namespacedName": "pt-shared-services/uc-stress-memory-419", "error": "exit status 1"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/server.go:187
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/grpc/utils.go:205
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3928
google.golang.org/grpc.(*Server).processUnaryRPC
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297
google.golang.org/grpc.(*Server).handleStream
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941
```

**Comment by WangXiangUSTC** [comment]
Could you please provide the stdout and stderr log related to the `byteman` of your Java application? 

It will help me to check whether the `byteman` agent is attached success.

**Comment by ywq20011** [comment]
my java application did not produce any log related to byteman..
i don't know where to find the logs..
bminstall.sh process produced the content below only:
```
com.sun.tools.attach.AgentLoadException: 102
com.sun.tools.attach.AgentLoadException: 100
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)
	at org.chaos_mesh.agent_installer.Install.injectAgent(Install.java:255)
	at org.chaos_mesh.agent_installer.Install.main(Install.java:48)

```

**Comment by WangXiangUSTC** [comment]
What is the java version of your application? I will try it

**Comment by WangXiangUSTC** [comment]
Unfortunately, I can't reproduce it in my environment. Could you please check whether the `byteman` agent is installed success into your java application by following steps:

1. Enter into the Java appliction's Pod

For example, if the Pod name is `test`, execute the command below:

```bash
kubectl exec -it test  /bin/sh
```

2. Send HTTP request to `byteman` agent

I see the YAML config file of your experiment, the port is 9277, so execute the command below:

```bash
curl -X GET 127.0.0.1:9277
```

check the result, the result will look like below if the agent is installed success:

```log
curl: (1) Received HTTP/0.9 when not allowed
```

**Comment by ywq20011** [comment]
pretty sure 9277 port is listened by something...
```
root@chaos-app-1-6d6c679fc7-9mghv:/# curl localhost:9277 -v
* Rebuilt URL to: localhost:9277/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9277 (#0)
> GET / HTTP/1.1
> Host: localhost:9277
> User-Agent: curl/7.52.1
> Accept: */*
> 
ERROR
Unexpected command GET / HTTP/1.1
OK
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact

```


in another container where agent is not installed:

```
root@chaos-app-2-85c4ccc46-5ptwt:/# curl localhost:9277 -v
* Rebuilt URL to: localhost:9277/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 9277 failed: Connection refused
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Cannot assign requested address
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Cannot assign requested address
* Failed to connect to localhost port 9277: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 9277: Connection refused

```

**Comment by WangXiangUSTC** [comment]
OK, it seems that the agent installed success, and  this error can be ignored, I will fix it

**Comment by ywq20011** [comment]
> OK, it seems that the agent installed success, and this error can be ignored, I will fix it

![image](https://user-images.githubusercontent.com/18238676/173774719-5da466fb-afd2-44f0-96a5-ac5ca7a25dd5.png)

the agent installed success, but, it seems that the injection is not?

![image](https://user-images.githubusercontent.com/18238676/173774934-3c84dec3-c6ac-4d5b-b213-06eb80bb742e.png)

**Comment by WangXiangUSTC** [comment]
> > OK, it seems that the agent installed success, and this error can be ignored, I will fix it
> 
> ![image](https://user-images.githubusercontent.com/18238676/173774719-5da466fb-afd2-44f0-96a5-ac5ca7a25dd5.png)
> 
> the agent installed success, but, it seems that the injection is not?
> 
> ![image](https://user-images.githubusercontent.com/18238676/173774934-3c84dec3-c6ac-4d5b-b213-06eb80bb742e.png)

It requires updating codes to ignore this error, please try later after I fix it.
