### ISSUE TITLE
Chaosctl reported "not implemented"

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3391]
## Bug Report

**What version of Kubernetes are you using?**
  

v1.22.8

**What version of Chaos Mesh are you using?**
 

2.2.0

**What did you do?**
. 

Use chaosctl to collect debug info https://github.com/chaos-mesh/chaos-mesh/issues/3382#issuecomment-1163869761

**What did you expect to see?** 

Return the debug infor

**What did you see instead?** 

```
	goroutine 16597 [running]:
	runtime/debug.Stack()
		/usr/local/go/src/runtime/debug/stack.go:24 +0x65
	runtime/debug.PrintStack()
		/usr/local/go/src/runtime/debug/stack.go:16 +0x19
	github.com/99designs/gqlgen/graphql.DefaultRecover({0xc00085b8f8?, 0x624698?}, {0x1f0e140?, 0xc001030690?})
		/tmp/go/pkg/mod/github.com/99designs/gqlgen@v0.17.2/graphql/recovery.go:17 +0x71
	github.com/99designs/gqlgen/graphql.(*OperationContext).Recover(0x4eab74?, {0x25cffe0, 0xc0013de2d0}, {0x1f0e140?, 0xc001030690?})
		/tmp/go/pkg/mod/github.com/99designs/gqlgen@v0.17.2/graphql/context_operation.go:114 +0x3e
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext)._RawIPSet_ipSetType.func1()
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:19021 +0x6a
	panic({0x1f0e140, 0xc001030690})
		/usr/local/go/src/runtime/panic.go:838 +0x207
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server.(*rawIPSetResolver).IPSetType(0xc00075b1d0?, {0x20?, 0xc00019e000?}, 0xc001240da0?)
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/schema.resolvers.go:1160 +0x3a
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext)._RawIPSet_ipSetType.func2({0x25cffe0?, 0xc0013de2d0})
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:19036 +0x84
	github.com/99designs/gqlgen/graphql/executor.processExtensions.func4({0x25cffe0?, 0xc0013de2d0?}, 0xc001b4ca80?)
		/tmp/go/pkg/mod/github.com/99designs/gqlgen@v0.17.2/graphql/executor/extensions.go:72 +0x26
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext)._RawIPSet_ipSetType(0xc000951fb0, {0x25cffe0, 0xc0013de120}, {0xc000548c00?, {0x0?, 0xc001030640?, 0xc00085bcd8?}}, 0xc00345c100)
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:19034 +0x283
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext)._RawIPSet.func2({0x25cffe0?, 0xc0013de120?})
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:28124 +0xb8
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext)._RawIPSet.func3()
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:28132 +0x25
	github.com/99designs/gqlgen/graphql.(*FieldSet).Dispatch(0xc000356050)
		/tmp/go/pkg/mod/github.com/99designs/gqlgen@v0.17.2/graphql/fieldset.go:34 +0x96
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext)._RawIPSet(0xc000951fb0, {0x25cffe0?, 0xc0013de120}, {0xc001b4c5a0, 0x6, 0x6}, 0xc00345c100)
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:28176 +0x245
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext).marshalNRawIPSet2githubᚗcomᚋchaosᚑmeshᚋchaosᚑmeshᚋapiᚋv1alpha1ᚐRawIPSet(...)
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:29730
	github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext).marshalORawIPSet2ᚕgithubᚗcomᚋchaosᚑmeshᚋchaosᚑmeshᚋapiᚋv1alpha1ᚐRawIPSetᚄ.func1(0x2)
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:31392 +0x1fd
	created by github.com/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated.(*executionContext).marshalORawIPSet2ᚕgithubᚗcomᚋchaosᚑmeshᚋchaosᚑmeshᚋapiᚋv1alpha1ᚐRawIPSetᚄ
		/home/runner/work/chaos-mesh/chaos-mesh/pkg/ctrl/server/generated/generated.go:31397 +0x39f
	not implemented
```

**Output of chaosctl**

**Comment by Andrewmatilde** [comment]
I fix it here ,https://github.com/chaos-mesh/chaos-mesh/pull/3346/files#diff-ac1419c1b5fa38a49329d5a1dba41ed5c444a05fd855a79c5f564d3d249f638eR1160.
Bug Integration Test have other problem 😂.
