### ISSUE TITLE
How do I perform a JVMChaos experiment through Byteman? I have some errors.

### ISSUE THREAD

**Issue by jwojnarowicz** [chaos-mesh/chaos-mesh#3520]
Hi everyone,
I have run into a problem while trying to test some example JVMChaos experiments following [docummentation](https://chaos-mesh.org/docs/simulate-jvm-application-chaos/).

**Version of Chaos Mesh**: 2.3.0

**What did I do?**

I have used the example file provided, so the **Java version** in the image is openjdk-16.

**What did I expect to see?**

In logs of the example pod:
```bash
Rule.execute called for return_0:0
return execute
caught ReturnException
9999. Hello World
```
as stated in docs.

**What did I get?**

Something like this periodically between test *hello worlds*:
```bash
Full thread dump OpenJDK 64-Bit Server VM (16-ea+32 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fba7070d410, length=11, elements={
0x00007fba89d2a010, 0x00007fba71822010, 0x00007fba71822550, 0x00007fba71822a90,
0x00007fba71816010, 0x00007fba71816550, 0x00007fba89d276b0, 0x00007fba89d27d10,
0x00007fba71816a90, 0x00007fba70704550, 0x00007fba70704a90
}

"main" #1 prio=5 os_prio=0 cpu=86.27ms elapsed=298.28s tid=0x00007fba89d2a010 nid=0x7 waiting on condition  [0x00007fba89e76000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@16-ea/Native Method)
        at HelloWorld.Main.main(Main.java:7)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.09ms elapsed=298.27s tid=0x00007fba71822010 nid=0x9 waiting on condition  [0x00007fba70fff000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.ref.Reference.waitForReferencePendingList(java.base@16-ea/Native Method)
        at java.lang.ref.Reference.processPendingReferences(java.base@16-ea/Reference.java:243)
        at java.lang.ref.Reference$ReferenceHandler.run(java.base@16-ea/Reference.java:215)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.17ms elapsed=298.27s tid=0x00007fba71822550 nid=0xa in Object.wait()  [0x00007fba70efe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@16-ea/Native Method)
        - waiting on <0x0000000623a0d370> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@16-ea/ReferenceQueue.java:155)
        - locked <0x0000000623a0d370> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@16-ea/ReferenceQueue.java:176)
        at java.lang.ref.Finalizer$FinalizerThread.run(java.base@16-ea/Finalizer.java:171)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=12.84ms elapsed=298.27s tid=0x00007fba71822a90 nid=0xb waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.07ms elapsed=298.27s tid=0x00007fba71816010 nid=0xc runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=0 cpu=5.47ms elapsed=298.27s tid=0x00007fba71816550 nid=0xd runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=8.80ms elapsed=298.27s tid=0x00007fba89d276b0 nid=0xe waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=37.24ms elapsed=298.27s tid=0x00007fba89d27d10 nid=0xf waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=0.11ms elapsed=298.27s tid=0x00007fba71816a90 nid=0x10 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Notification Thread" #10 daemon prio=9 os_prio=0 cpu=0.07ms elapsed=298.25s tid=0x00007fba70704550 nid=0x11 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=0 cpu=0.38ms elapsed=298.25s tid=0x00007fba70704a90 nid=0x13 in Object.wait()  [0x00007fba704fe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@16-ea/Native Method)
        - waiting on <0x0000000623a7d9c8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(java.base@16-ea/ReferenceQueue.java:155)
        - locked <0x0000000623a7d9c8> (a java.lang.ref.ReferenceQueue$Lock)
        at jdk.internal.ref.CleanerImpl.run(java.base@16-ea/CleanerImpl.java:140)
        at java.lang.Thread.run(java.base@16-ea/Thread.java:831)
        at jdk.internal.misc.InnocuousThread.run(java.base@16-ea/InnocuousThread.java:134)

"VM Thread" os_prio=0 cpu=72.68ms elapsed=298.27s tid=0x00007fba72465330 nid=0x8 runnable

"VM Periodic Task Thread" os_prio=0 cpu=106.86ms elapsed=298.25s tid=0x00007fba72465660 nid=0x12 waiting on condition

JNI global refs: 7, weak refs: 0

Heap
 def new generation   total 146880K, used 7837K [0x0000000623a00000, 0x000000062d950000, 0x00000006c26a0000)  eden space 130624K,   6% used [0x0000000623a00000, 0x00000006241a76a8, 0x000000062b990000)
  from space 16256K,   0% used [0x000000062b990000, 0x000000062b990000, 0x000000062c970000)
  to   space 16256K,   0% used [0x000000062c970000, 0x000000062c970000, 0x000000062d950000)
 tenured generation   total 326336K, used 0K [0x00000006c26a0000, 0x00000006d6550000, 0x0000000800000000)
   the space 326336K,   0% used [0x00000006c26a0000, 0x00000006c26a0000, 0x00000006c26a0200, 0x00000006d6550000)
 Metaspace       used 287K, committed 512K, reserved 1056768K
  class space    used 6K, committed 128K, reserved 1048576K

298. Hello World
...
```

**Fragment of logs of chaos-daemon which i think repeats a few times**:

```bash
2022-08-03T10:11:33.324Z  ERROR   chaos-daemon.daemon-server      chaosdaemon/server.go:187       [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset.
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/2772/root/tmp/.java_pid2772: target process 2772 doesn't respond within 10500ms or HotSpot VM not loaded
[0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset.
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/2772/root/tmp/.java_pid2772: target process 2772 doesn't respond within 10500ms or HotSpot VM not loaded
        at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100)
        at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
        at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
        at org.chaos_mesh.agent_installer.Install.attach(Install.java:203)
        at org.chaos_mesh.agent_installer.Install.main(Install.java:47)
        {"namespacedName": "helloworld/return", "error": "exit status 1"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1
        /home/runner/work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/server.go:187
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
        /home/runner/work/chaos-mesh/chaos-mesh/pkg/grpc/utils.go:205
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler
        /home/runner/work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:4441
google.golang.org/grpc.(*Server).processUnaryRPC
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297
google.golang.org/grpc.(*Server).handleStream
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941
2022-08-03T10:11:33.381Z        INFO    chaos-daemon.daemon-server      chaosdaemon/server.go:187       InstallJVMRules {"namespacedName": "helloworld/return", "request": "container_id:\"docker://d1c051151217c12783c06fccdf5024f9298abefe6780ff8ec464e1ad83d06622\"  rule:\"\\nRULE Main-getnum-return-1659519606\\nCLASS Main\\nMETHOD getnum\\nAT ENTRY\\nIF true\\nDO\\n\\treturn 9999;\\nENDRULE\\n\"  port:9277  enterNS:true"}
2022-08-03T10:11:33.385Z        INFO    chaos-daemon.daemon-server      chaosdaemon/jvm_server.go:50    get flatTree    {"namespacedName": "helloworld/return", "source": 2772, "flatTree": []}
2022-08-03T10:11:33.385Z        INFO    chaos-daemon.daemon-server.background-process-manager.process-builder   pb/chaosdaemon.pb.go:4439  build command    {"namespacedName": "helloworld/return", "command": "/usr/local/bin/nsexec -m /proc/2772/ns/mnt -- sh -c mkdir -p /usr/local/byteman/lib/"}
2022-08-03T10:11:33.388Z        INFO    chaos-daemon.daemon-server.background-process-manager.process-builder   chaosdaemon/jvm_server.go:8build command    {"namespacedName": "helloworld/return", "command": "/usr/local/bin/nsexec -m /proc/2772/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman.jar"}
2022-08-03T10:11:33.391Z        INFO    chaos-daemon.daemon-server.background-process-manager.process-builder   chaosdaemon/jvm_server.go:8build command    {"namespacedName": "helloworld/return", "command": "/usr/local/bin/nsexec -m /proc/2772/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman-helper.jar"}
2022-08-03T10:11:33.394Z        INFO    chaos-daemon.daemon-server.background-process-manager.process-builder   chaosdaemon/jvm_server.go:9build command    {"namespacedName": "helloworld/return", "command": "/usr/local/bin/nsexec -m /proc/2772/ns/mnt -- sh -c cat > /usr/local/byteman/lib/chaos-agent.jar"}
2022-08-03T10:11:33.396Z        INFO    chaos-daemon.daemon-server.background-process-manager.process-builder   pb/chaosdaemon.pb.go:4439  build command    {"namespacedName": "helloworld/return", "command": "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compileToBytecode -p 9277 2772"}
2022-08-03T10:11:54.949Z        ERROR   chaos-daemon.daemon-server      chaosdaemon/server.go:187       [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset.
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/2772/root/tmp/.java_pid2772: target process 2772 doesn't respond within 10500ms or HotSpot VM not loaded
```
**Screenshot form Chaos Dashboard Events:**
![image](https://user-images.githubusercontent.com/72974897/182586217-ab357482-0941-4607-9eb5-2c29f1ba6e96.png)

If someone can help through testing and maybe guiding to resolve this issue please respond. I was just following the docs, so any further information how does this Chaos perform would be strongly appreciated. Thanks in advance :)

**Comment by WangXiangUSTC** [comment]
it is similar with https://github.com/chaos-mesh/chaos-mesh/issues/2588, could you please make sure the Linux kernel is  v4.1 or later?

**Comment by jwojnarowicz** [comment]
> it is similar with #2588, could you please make sure the Linux kernel is v4.1 or later?

It is lower, that might be the case. Thanks.
