### ISSUE TITLE
Exec format error when run io-latency test on arm platform

### ISSUE THREAD

**Issue by zjyzju** [chaos-mesh/chaos-mesh#3619]
## Bug Report

What version of Kubernetes are you using?
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/arm64"}

What version of Chaos Mesh are you using?
Controller manager Version: version.Info{GitVersion:"v2.3.0", GitCommit:"3d299ed0f800b71842a7806c59ccc9a2abca3d38", BuildDate:"2022-07-29T10:00:48Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/arm64"}

What did you do?
install chaosMesh by:
curl -sSL https://mirrors.chaos-mesh.org/v2.3.0/install.sh | bash -s -- --runtime containerd

run io-latency test by yaml:
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-latency
  namespace: chaos-mesh
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: lcdp-platform
  volumePath: /opt/lcdp/logs
  path: '/opt/lcdp/logs/**/*'
  delay: '2s'
  percent: 50
  duration: '400s'	

**What did you expect to see?**
io latency delayed 2s

**What did you see instead?**
Warning  Failed           23s   records       Failed to apply chaos: fialed to apply for pod default/lcdp-platform-deployment-5cfd6994d4-57r8d: rpc error: code = Unknown desc = toda startup takes too long or an error occurs:

**Output of chaosctl**

2022-09-08T06:47:27.935Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	Starting toda takes too long or encounter an error	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d"}
2022-09-08T06:47:27.935Z	INFO	chaos-daemon.daemon-server.background-process-manager	bpm/bpm.go:247	process stopped	{"uid": "68c072e9-6ec2-4717-99b7-9ad22b093db8", "pid": 172448}
2022-09-08T06:47:27.935Z	INFO	chaos-daemon.daemon-server.background-process-manager	bpm/bpm.go:309	Successfully killed process	{"uid": "68c072e9-6ec2-4717-99b7-9ad22b093db8"}
2022-09-08T06:47:27.935Z	INFO	chaos-daemon.daemon-server	pb/chaosdaemon.pb.go:4349	kill toda successfully	{"uid": "68c072e9-6ec2-4717-99b7-9ad22b093db8"}
2022-09-08T06:52:55.624Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	applying io chaos	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d", "Request": "actions:\"[{\\\"type\\\":\\\"latency\\\",\\\"path\\\":\\\"/opt/lcdp/logs/**/*\\\",\\\"percent\\\":50,\\\"faults\\\":[{\\\"errno\\\":0,\\\"weight\\\":1}],\\\"latency\\\":\\\"2s\\\",\\\"source\\\":\\\"chaos-mesh/io-latency\\\"}]\"  volume:\"/opt/lcdp/logs\"  container_id:\"containerd://0daeae246aa1082cf455e2d61a4a845e057050c845de38e4a8ae0c166f4eccad\"  enterNS:true"}
2022-09-08T06:52:55.624Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	the length of actions	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d", "length": 1}
2022-09-08T06:52:55.626Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	executing	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d", "cmd": "/usr/local/bin/toda --path /opt/lcdp/logs --verbose info"}
2022-09-08T06:52:55.626Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4349	build command	{"command": "/usr/local/bin/nsexec -l -p /proc/144376/ns/pid -m /proc/144376/ns/mnt -- /usr/local/bin/toda --path /opt/lcdp/logs --verbose info"}
2022-09-08T06:52:55.627Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	Waiting for toda to start	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d"}
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 8, kind: Other, message: "Exec format error" }', src/main.rs:108:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:520
  11: rust_begin_unwind
             at src/libstd/panicking.rs:431
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: nsexec::main
  15: std::rt::lang_start::{{closure}}
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:342
  18: std::panicking::try
             at src/libstd/panicking.rs:319
  19: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  20: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  21: main
  22: __libc_start_main
  23: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2022-09-08T06:52:55.649Z	INFO	chaos-daemon.daemon-server.background-process-manager	bpm/bpm.go:247	process stopped	{"uid": "bde0e2fd-28bd-45ae-8f95-cc783d408e46", "pid": 175492}
2022-09-08T06:52:55.649Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	Starting toda takes too long or encounter an error	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d"}
2022-09-08T06:52:55.649Z	ERROR	chaos-daemon.daemon-server	chaosdaemon/server.go:187	kill toda	{"namespacedName": "default/lcdp-platform-deployment-5cfd6994d4-57r8d", "request": "actions:\"[{\\\"type\\\":\\\"latency\\\",\\\"path\\\":\\\"/opt/lcdp/logs/**/*\\\",\\\"percent\\\":50,\\\"faults\\\":[{\\\"errno\\\":0,\\\"weight\\\":1}],\\\"latency\\\":\\\"2s\\\",\\\"source\\\":\\\"chaos-mesh/io-latency\\\"}]\"  volume:\"/opt/lcdp/logs\"  container_id:\"containerd://0daeae246aa1082cf455e2d61a4a845e057050c845de38e4a8ae0c166f4eccad\"  enterNS:true", "error": "kill toda bde0e2fd-28bd-45ae-8f95-cc783d408e46: failed to find process with uid bde0e2fd-28bd-45ae-8f95-cc783d408e46", "errorVerbose": "failed to find process with uid bde0e2fd-28bd-45ae-8f95-cc783d408e46\ngithub.com/chaos-mesh/chaos-mesh/pkg/bpm.(*BackgroundProcessManager).KillBackgroundProcess\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/bpm/bpm.go:300\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).killIOChaos\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/iochaos_server.go:126\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).ApplyIOChaos\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/iochaos_server.go:110\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ApplyIOChaos_Handler.func1\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:4349\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/server.go:187\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/grpc/utils.go:205\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ApplyIOChaos_Handler\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:4351\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1259\nkill toda bde0e2fd-28bd-45ae-8f95-cc783d408e46\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).killIOChaos\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/iochaos_server.go:128\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).ApplyIOChaos\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/iochaos_server.go:110\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ApplyIOChaos_Handler.func1\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:4349\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/server.go:187\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/grpc/utils.go:205\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1\n\t/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34\ngithub.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ApplyIOChaos_Handler\n\t/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:4351\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.2\n\t/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1259"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.MetadataExtractor.func1
	/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/server.go:187
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
	/runner/_work/chaos-mesh/chaos-mesh/pkg/grpc/utils.go:205
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_ApplyIOChaos_Handler
	/runner/_work/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb/chaosdaemon.pb.go:4351
google.golang.org/grpc.(*Server).processUnaryRPC
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297
google.golang.org/grpc.(*Server).handleStream
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941

**Comment by STRRL** [comment]
Sorry, IOChaos does not support ARM now.
