### ISSUE TITLE
jvm chaos no support Pod contains more containerd

### ISSUE THREAD

**Issue by linyongluis** [chaos-mesh/chaos-mesh#3676]
## Bug Report

**What version of Kubernetes are you using?**

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.7-r0-CCE21.11.1.B007", GitCommit:"72ec45c44d6c2b26d75b3230869f755f1338fcd1", GitTreeState:"clean", BuildDate:"2021-12-02T09:22:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v2.3.0", GitCommit:"3d299ed0f800b71842a7806c59ccc9a2abca3d38", BuildDate:"2022-07-29T10:00:50Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**

config Jvm chaos inject pod

**What did you expect to see?**
jvm chaos successed

**What did you see instead?**
Failed to apply chaos: rpc error: code = Unknown desc = [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-run/io.containerd.runtime.v2.task/k8s.io/3c26fa6b02321fedae83afc8feddd77af1a3c6e33db77eed19d44637ef9f1739/rootfs/sys/fs/cgroup/cpuset. [0.002s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset. java.io.IOException: No such process [0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-run/io.containerd.runtime.v2.task/k8s.io/3c26fa6b02321fedae83afc8feddd77af1a3c6e33db77eed19d44637ef9f1739/rootfs/sys/fs/cgroup/cpuset. [0.002s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset. java.io.IOException: No such process at jdk.attach/sun.tools.attach.VirtualMachineImpl.sendQuitTo(Native Method) at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:78) at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58) at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207) at org.chaos_mesh.agent_installer.Install.attach(Install.java:203) at org.chaos_mesh.agent_installer.Install.main(Install.java:47) : exit status 1

**Output of chaosctl**

**Comment by linyongluis** [comment]
Pod contains two container , the first container is consul , the second container is java  application ， but exec jvm chaos injected consul containerd .

**Comment by MimeLyc** [comment]
Hey @linyongluis , I found some comment related to this issue in the selector of JVMChaos in file `api/v1alpha1/selector.go` ⬇️ 
https://github.com/chaos-mesh/chaos-mesh/blob/d1e08a5d3bc73e1f2645aa88a0737718fa04c171/api/v1alpha1/selector.go#L121
```go
type ContainerSelector struct {
	PodSelector `json:",inline"`

	// ContainerNames indicates list of the name of affected container.
	// If not set, the first container will be injected
	// +optional
	ContainerNames []string `json:"containerNames,omitempty"`
}
```
And the select logic related to `ContainerSelector` in file `pkg/selector/container/selector.go` proves this comment, so maybe you should specify the `containerNames` in your selector explicitly.

---
Hi @STRRL , I firstly tried to completely solve this issue by setting all container metas into records, but I found above comment & implementation.
So maybe this 'issue' was by design or workaround for some reason, I think I shouldn't modify the implementation rashly.

May I just append the description & default logic of ContainerSelector to the related doc( https://github.com/chaos-mesh/website/blob/master/docs/define-chaos-experiment-scope.md ) and we can see whether we should support inject to all containers if `ContainerNames` not specified afterwards?

**Comment by Jacob-at-Ericsson-dot-com** [comment]
Hi, is this issue still open?

**Comment by barbierajput378-pixel** [comment]
Hi! I started looking into this issue and wanted to confirm whether it's still open before continuing. Please let me know if someone is already working on it.

**Comment by spencercjh** [comment]
@barbierajput378-pixel I think there is no one working on it.

**Comment by barbierajput378-pixel** [comment]
@spencercjh 


yea guess u're right

**Comment by Yash121l** [comment]
I would like to work on this. Plan: make the JVMChaos container selection honour the container name from the spec instead of falling back to the first container when a pod has several, following the selector comment in `api/v1alpha1/selector.go`, with a unit test for a multi-container pod.

**Comment by Yash121l** [comment]
Opened #5096. The cause is the shared container selector defaulting to `pod.Spec.Containers[0]` when `containerNames` is empty, which on your pod was `consul` rather than the Java container. With `containerNames` set the right container was already used, so the PR makes the multi-container case without `containerNames` an explicit error instead of a silent guess, and adds tests for both paths.
