### ISSUE TITLE
Inject JVMChaos Failed: Failed to process request: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by johnna2020** [chaos-mesh/chaos-mesh#3735]
## Bug Report

**What version of Kubernetes are you using?**
v1.21.1

**What version of Chaos Mesh are you using?**
2.4.1

**What did you do? / Minimal Reproducible Example**
Inject JVMChaos
`_kind: JVMChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: perf1
  name: stack-oom-fss
spec:
  selector:
    namespaces:
      - perf1
    labelSelectors:
      app: perf1-fss1
  mode: all
  duration: 1m
  action: stress
  port: 9277
  memType: stack
  name: '--stress-1667272408'
  value: ''
  exception: ''
  latency: 0
  ruleData: ''_`

**What did you expect to see?**
JVM OOM

**What did you see instead?**
chaos-daemon log:
`InstallJVMRules	{"namespacedName": "perf1/stack-oom-fss", "request": "container_id:\"docker://86f950a9e392604b98ebb1de2ecd9ac0647154ac3ca4feb6458e262e04306980\" rule:\"\\nRULE --stress-1667272408\\nCLASS org.chaos_mesh.chaos_agent.TriggerThread\\nMETHOD triggerFunc\\nHELPER org.chaos_mesh.byteman.helper.StressHelper\\nAT ENTRY\\nBIND flag:boolean=true;\\nIF true\\nDO\\n\\tinjectMemStress(\\\"--stress-1667272408\\\", \\\"stack\\\");\\nENDRULE\\n\" port:9277 enterNS:true"}
2022-11-01T03:21:02.033Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	create btm file	{"namespacedName": "perf1/stack-oom-fss", "file": "/tmp/rule.btm2271810983"}
2022-11-01T03:21:02.033Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4457	build command	{"namespacedName": "perf1/stack-oom-fss", "command": "/usr/local/bin/nsexec -n /proc/3752986/ns/net -- sh -c bmsubmit.sh -p 9277 -u /tmp/rule.btm2271810983"}
2022-11-01T03:21:02.159Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	[0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset.
uninstall RULE --stress-1667272408

	{"namespacedName": "perf1/stack-oom-fss"}
`
**exec the command '/usr/local/bin/nsexec -n /proc/3752986/ns/net -- sh -c bmsubmit.sh -p 9277 -u /tmp/rule.btm2271810983' in chaos-daemon pod**:
the output:
```
root@chaos-daemon-mnkxh:/# /usr/local/bin/nsexec -n /proc/3754354/ns/net -- sh -c bmsubmit.sh -p 9277 -l /tmp/rule.btm1861200382
[0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /host-sys/fs/cgroup/cpuset.
Failed to process request: java.net.ConnectException: Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/java.net.Socket.connect(Socket.java:558)
	at java.base/java.net.Socket.<init>(Socket.java:454)
	at java.base/java.net.Socket.<init>(Socket.java:231)
	at org.jboss.byteman.agent.submit.Submit$Comm.<init>(Submit.java:881)
	at org.jboss.byteman.agent.submit.Submit.submitRequest(Submit.java:787)
	at org.jboss.byteman.agent.submit.Submit.listAllRules(Submit.java:176)
	at org.jboss.byteman.agent.submit.Submit.main(Submit.java:1121)
```
 i think the agent is installed success because i see this:
![image](https://user-images.githubusercontent.com/117137103/199163093-81336899-51b1-422e-a501-26975de48cec.png)

**Comment by cwen0** [comment]
@johnna2020  What version of JAVA are you using?

**Comment by johnna2020** [comment]
java8

**Comment by johnna2020** [comment]
later i find that there are execptions in injected pod: so it's unsupported?
```
Setting org.jboss.byteman.transform.all=
Setting org.jboss.byteman.verbose=
Setting org.jboss.byteman.compileToBytecode=
AccessManager:init Initialising default AccessManager
TransformListener() : accepting requests on localhost:9277
Exception in thread "Attach Listener" java.lang.UnsupportedClassVersionError: org/chaos_mesh/chaos_agent/ChaosAgent has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Agent failed to start!
TransformListener() : handling connection on port 9277
TransformListener() : handling connection on port 9277


```

**Comment by cwen0** [comment]
> later i find that there are execptions in injected pod: so it's unsupported to Java8?
> 
> ```
> Setting org.jboss.byteman.transform.all=
> Setting org.jboss.byteman.verbose=
> Setting org.jboss.byteman.compileToBytecode=
> AccessManager:init Initialising default AccessManager
> TransformListener() : accepting requests on localhost:9277
> Exception in thread "Attach Listener" java.lang.UnsupportedClassVersionError: org/chaos_mesh/chaos_agent/ChaosAgent has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
> 	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
> Agent failed to start!
> TransformListener() : handling connection on port 9277
> TransformListener() : handling connection on port 9277
> ```

Yes, this version was built on java 11. So java8 was not supported. 

If you have time, you can help to upgrade byteman-helper to v4.0.18-0.12. I have fixed this issue on  byteman-helper v4.0.18-0.12. You can just update the URL at https://github.com/chaos-mesh/chaos-mesh/blob/master/images/chaos-daemon/Dockerfile#L22
https://github.com/chaos-mesh/chaos-mesh/blob/master/images/chaos-daemon/Dockerfile#L33

**Comment by johnna2020** [comment]
> > later i find that there are execptions in injected pod: so it's unsupported to Java8?
> > ```
> > Setting org.jboss.byteman.transform.all=
> > Setting org.jboss.byteman.verbose=
> > Setting org.jboss.byteman.compileToBytecode=
> > AccessManager:init Initialising default AccessManager
> > TransformListener() : accepting requests on localhost:9277
> > Exception in thread "Attach Listener" java.lang.UnsupportedClassVersionError: org/chaos_mesh/chaos_agent/ChaosAgent has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> > 	at java.lang.ClassLoader.defineClass1(Native Method)
> > 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> > 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> > 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
> > 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
> > 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
> > 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
> > 	at java.security.AccessController.doPrivileged(Native Method)
> > 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
> > 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
> > 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
> > 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
> > 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
> > 	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
> > Agent failed to start!
> > TransformListener() : handling connection on port 9277
> > TransformListener() : handling connection on port 9277
> > ```
> 
> Yes, this version was built on java 11. So java8 was not supported.
> 
> If you have time, you can help to upgrade byteman-helper to v4.0.18-0.12. I have fixed this issue on byteman-helper [v4.0.18-0.12](https://github.com/chaos-mesh/byteman-helper/pull/15). You can just update the URL at https://github.com/chaos-mesh/chaos-mesh/blob/master/images/chaos-daemon/Dockerfile#L22 https://github.com/chaos-mesh/chaos-mesh/blob/master/images/chaos-daemon/Dockerfile#L24

Of course it's OK. But I try to exec chaos-daemon pod and replace byteman v4.0.18-0.9 to v4.0.18-0.12. 
my operation: 
```
rm -rf /usr/local/byteman*
curl -L https://mirrors.chaos-mesh.org/byteman-chaos-mesh-download-v4.0.18-0.12.tar.gz -o /usr/local/byteman.tar.gz
tar xvf /usr/local/byteman.tar.gz -C /usr/local
mv /usr/local/byteman-chaos-mesh-download-v4.0.18-0.12 /usr/local/byteman
```
And it didn't work, the exception is 
```
Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.Exception: Main : attempting to load Byteman agent more than once
	at org.jboss.byteman.agent.Main.premain(Main.java:57)
	at org.jboss.byteman.agent.Main.agentmain(Main.java:309)
	... 6 more
Agent failed to start!
Exception in thread "Attach Listener" java.lang.ClassNotFoundException: org.chaos_mesh.chaos_agent.ChaosAgent
	at java.net.URLClassLoader$1.run(URLClassLoader.java:371)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.util.zip.ZipException: invalid code lengths set
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at sun.misc.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:1003)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	... 8 more
Agent failed to start!

```
and i want to know whether it's  the right way

**Comment by cwen0** [comment]
@johnna2020 You can try to change the java version of chaos-daemon to java8.

**Comment by johnna2020** [comment]
> @johnna2020 You can try to change the java version of chaos-daemon to java8.

ok, thanks, i'll try it
