### ISSUE TITLE
chaos-dashboard does not work.

### ISSUE THREAD

**Issue by lhh-yeah** [chaos-mesh/chaos-mesh#4101]
## Bug Report

**What version of Kubernetes are you using?**

1.24.4

**What version of Chaos Mesh are you using?**

2.6.0

**What did you do? / Minimal Reproducible Example**

chaos-dashboard does not work, container keeps restarting.
![image](https://github.com/chaos-mesh/chaos-mesh/assets/15073577/dc4eb95a-9231-4abb-a1fe-f812823e69bd)

chaos-dashboard error log：
```
E0628 03:38:08.564507       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 250 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2ab5e00?, 0x46f1ea0})
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000756980?})
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/runtime/runtime.go:49 +0x75
panic({0x2ab5e00, 0x46f1ea0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/store/workflow.(*WorkflowStore).DeleteByFinishTime(0xc000116808, {0xc0004bc870?, 0x203000?}, 0x2260ff9290000?)
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/store/workflow/workflow.go:118 +0xe0
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller.(*Controller).runWorker(0xc0003efe00)
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller/ttlcontroller.go:77 +0xf0
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x357a060, 0xc000849d40}, 0x1, 0xc00044a360)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x274a48a78000, 0x0, 0x0?, 0x0?)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:92 +0x25
created by github.com/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller.Register
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller/ttlcontroller.go:65 +0x155
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x27d4200]

goroutine 250 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000756980?})
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x2ab5e00, 0x46f1ea0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/store/workflow.(*WorkflowStore).DeleteByFinishTime(0xc000116808, {0xc0004bc870?, 0x203000?}, 0x2260ff9290000?)
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/store/workflow/workflow.go:118 +0xe0
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller.(*Controller).runWorker(0xc0003efe00)
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller/ttlcontroller.go:77 +0xf0
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x357a060, 0xc000849d40}, 0x1, 0xc00044a360)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x274a48a78000, 0x0, 0x0?, 0x0?)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.26.1/pkg/util/wait/wait.go:92 +0x25
created by github.com/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller.Register
	/home/runner/work/chaos-mesh/chaos-mesh/pkg/dashboard/ttlcontroller/ttlcontroller.go:65 +0x155
```

source code：
![image](https://github.com/chaos-mesh/chaos-mesh/assets/15073577/28b9b820-4564-44e9-b95d-b5950814fb5f)

db data：
<img width="974" alt="image" src="https://github.com/chaos-mesh/chaos-mesh/assets/15073577/0e203885-ddff-49f7-a5f4-5927d91d018f">

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by g1eny0ung** [comment]
Hi @lhh-yeah, the `v2.6.1` fixes this problem and it's already released. Please upgrade and see if there is still this problem.
