### ISSUE TITLE
JVMChaos Failed to apply chaos: rpc error: code = Unknown desc = exit status 1

### ISSUE THREAD

**Issue by shaochun0530** [chaos-mesh/chaos-mesh#4179]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: v1.28.1
Server Version: v1.23.17
**What version of Chaos Mesh are you using?**

2.5.1
**What did you do? / Minimal Reproducible Example**

Create a JVMChaos with latency & Exception, both select the port for non-using port.
What i have checked 

- [x] 1. Linux Kernel Version 5.15.0-69-generic
- [x] 2. Check byteman-jar, byteman-helper-jar, chaos-agent.jar exist in application pods 
- [x] 3. Java 8
- [x] 4. curl 127.0.0.1:9277 **failed** (i select 9277 as my port configuration) In my understanding, with the port configuration i should select a port which is not been used?
- [ ] 5. Should i check namespace contains the label for Admission Webhook?

**What did you see instead?**
**On chaos mesh UI**
the experiments are both in Injecting Status.
Both shows `Failed to apply chaos: rpc error: code = Unknown desc = exit status 1 `.
**Application Logs:**
Latency Experiment
Agent failed to start!       
│ Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
│     at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
│     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
│     at java.lang.reflect.Method.invoke(Method.java:498)
│     at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
│     at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
│ Caused by: java.lang.Exception: Main : attempting to load Byteman agent more than once
│     at org.jboss.byteman.agent.Main.premain(Main.java:57)
│     at org.jboss.byteman.agent.Main.agentmain(Main.java:309)
│     ... 5 more
│ Agent failed to start!
│ Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
│     at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
│     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
│     at java.lang.reflect.Method.invoke(Method.java:498)
│     at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
│     at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
│ Caused by: java.lang.Exception: Main : attempting to load chaos agent more than once
│     at org.chaos_mesh.chaos_agent.ChaosAgent.premain(ChaosAgent.java:43)
│     at org.chaos_mesh.chaos_agent.ChaosAgent.agentmain(ChaosAgent.java:53) 
│     ... 5 more

Exception Experiment:
Nothing on AP logs.

**Comment by shaochun0530** [comment]
i get logs from daemon
Failed to process request: java.net.ConnectException: Connection refused (Connection refused) 
-- Args were: [/usr/local/byteman/lib/byteman-helper.jar]
java.net.ConnectException: Connection refused (Connection refused)...

**Comment by ziidu** [comment]
This should be an error in the execution of your bminstall.sh script; please check the execution result of bminstall.sh.

**Comment by ziidu** [comment]
chaos-mesh JVMChaos fault injection does not support JDK8, please see #4184.
