### ISSUE TITLE
JVM fault injection should rely on the target container's jdk environment

### ISSUE THREAD

**Issue by ziidu** [chaos-mesh/chaos-mesh#4184]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now, the JVM fault injection uses the jdk which is version 11 in chaos-daemon. this will probably lead to problems with JVM fault injection failures if the jdk version of the target container's does not match the jdk version of chaos-daemon.example:

**[chaos-mesh/examples/jvm/app.yaml]**
```yaml
FROM openjdk:8
COPY Main.jar Main.jar
COPY Manifest.txt Manifest.txt
ENTRYPOINT ["java", "-jar", "Main.jar"]
```
```shell
kubectl apply -f chaos-mesh/examples/jvm/app.yaml
kubectl apply -f chaos-mesh/examples/jvm/jvm-return-example.yaml
```
I will find the following logs in chaos-daemon
```
2023-09-11T02:12:38.111Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4448	build command	{"namespacedName": "default/return", "command": "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compileToBytecode -p 9277 50299"}
2023-09-11T02:12:59.738Z	ERROR	chaos-daemon.daemon-server	chaosdaemon/server.go:187	com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/50299/root/tmp/.java_pid1: target process 50299 doesn't respond within 10500ms or HotSpot VM not loaded
com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/50299/root/tmp/.java_pid1: target process 50299 doesn't respond within 10500ms or HotSpot VM not loaded
	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at org.chaos_mesh.agent_installer.Install.attach(Install.java:203)
	at org.chaos_mesh.agent_installer.Install.main(Install.java:47)
	{"namespacedName": "default/return", "error": "exit status 1"}
```

**Describe the feature you'd like:**

JVM fault injection should rely on the target container's jdk environment

**Describe alternatives you've considered:**

1. chaos-daemon no longer installs jdk.
2. Copy BYTEMAN_HOME to the target container.
3. Get the environment variables of the target container, such as JAVA_HOME, PATH.
4. get the process ID(which usually is 1) of the target container.
5. Execute `bminstall.sh` and `bmsubmit.sh` commands in the target container to realize fault injection.

**Comment by shaochun0530** [comment]
so now jvmchaos only support JAVA 11, which is not above. Am i right? Thanks.
