### ISSUE TITLE
JVMChaos get ERROR Response "Failed to apply chaos: rpc error: code = Unknown"

### ISSUE THREAD

**Issue by kongliangliang** [chaos-mesh/chaos-mesh#4262]
环境信息：k8s集群

特殊信息：
应用进程只有1个java服务，但启动脚本里没有任何有关服务名的信息。进程pid=1
![image](https://github.com/chaos-mesh/chaos-mesh/assets/8425603/0df46b42-f628-45aa-8444-0874b30ea920)

报错信息：
Failed to apply chaos: rpc error: code = Unknown desc = com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/461625/root/tmp/.java_pid461625: target process 461625 doesn't respond within 10500ms or HotSpot VM not loaded com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/461625/root/tmp/.java_pid461625: target process 461625 doesn't respond within 10500ms or HotSpot VM not loaded at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100) at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58) at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207) at org.chaos_mesh.agent_installer.Install.attach(Install.java:203) at org.chaos_mesh.agent_installer.Install.main(Install.java:47) : exit status 1

截图信息：
![image](https://github.com/chaos-mesh/chaos-mesh/assets/8425603/b4cdb7b1-b90a-4357-a6c2-ca22b9769174)

所以是不是因为无法匹配到pid导致上述报错。如果是，现有平台通过何种方式，可以匹配到pid=1的服务呢？

**Comment by cwen0** [comment]
@kongliangliang Can you provider the pod config?
