### ISSUE TITLE
app log report：“ unknown helper class org.chaos_mesh.byteman.helper.SQLHelper ” when jvm-mysql insert

### ISSUE THREAD

**Issue by huangyanhong** [chaos-mesh/chaos-mesh#4460]
## Bug Report

**What version of Kubernetes are you using?**

k8s:v1.24.6 

**What version of Chaos Mesh are you using?**

2.6.3 

**What did you do? / Minimal Reproducible Example**
my-app is jboss start , use mybatis connect  mysql db ,when I  insert MYSQL  error into my app, it report the errors below ：
0m[0m13:34:38,469 INFO  [stdout] (Thread-117) org.jboss.byteman.agent.Transformer : possible trigger for rule --mysql-1721972077 in class com.mysql.cj.NativeSession
[0m[0m13:34:38,504 INFO  [stdout] (Thread-117) RuleTriggerMethodAdapter.injectTriggerPoint : inserting trigger into com.mysql.cj.NativeSession.execSQL(com.mysql.cj.Query,java.lang.String,int,com.mysql.cj.protocol.a.NativePacketPayload,boolean,com.mysql.cj.protocol.ProtocolEntityFactory,com.mysql.cj.protocol.ColumnDefinition,boolean) com.mysql.cj.protocol.Resultset for rule --mysql-1721972077
[0m[0m13:34:38,510 INFO  [stdout] (Thread-117) org.jboss.byteman.agent.Transformer : inserted trigger for --mysql-1721972077 in class com.mysql.cj.NativeSession
[0m[0m13:34:46,639 INFO  [stdout] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) Rule.execute called for --mysql-1721972077_0:0
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) Rule.ensureTypeCheckedCompiled : error type checking rule --mysql-1721972077
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) org.jboss.byteman.rule.exception.TypeException: Rule.typecheck : unknown helper class org.chaos_mesh.byteman.helper.SQLHelper for rule --mysql-1721972077
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at org.jboss.byteman.rule.Rule.ensureHelperClass(Rule.java:1010)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at org.jboss.byteman.rule.Rule.typeCheck(Rule.java:576)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at org.jboss.byteman.rule.Rule.ensureTypeCheckedCompiled(Rule.java:529)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at org.jboss.byteman.rule.Rule.execute(Rule.java:808)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at org.jboss.byteman.rule.Rule.execute(Rule.java:789)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at com.mysql.cj.NativeSession.execSQL(NativeSession.java)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2046)
[0m[31m13:34:46,641 ERROR [stderr] (QuartzScheduler_AssassinScheduler-assassin-serd1789233720998371328-75685c9684-flf7z1721030052466_MisfireHandler) 	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:604)

**What did you expect to see?**
when I query mysql return boom error

**What did you see instead?**
when I query mysql return  normal 

**Output of chaosctl**
damonset  log：
2024-07-26T05:34:37.288Z	INFO	chaos-daemon.daemon-server	util/util.go:112	get flatTree	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "source": 31861, "flatTree": []}
2024-07-26T05:34:37.288Z	INFO	chaos-daemon.daemon-server	util/util.go:112	get flatTree	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "source": 31789, "flatTree": []}
2024-07-26T05:34:37.288Z	INFO	chaos-daemon.daemon-server	chaosdaemon/jvm_server.go:48	get flatTree	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "source": 31776, "flatTree": [31861, 31789]}
2024-07-26T05:34:37.288Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4448	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "/usr/local/bin/nsexec -m /proc/31861/ns/mnt -- sh -c mkdir -p /usr/local/byteman/lib/"}
2024-07-26T05:34:37.295Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	chaosdaemon/jvm_server.go:87	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "/usr/local/bin/nsexec -m /proc/31861/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman.jar"}
2024-07-26T05:34:37.301Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	copy	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "jar name": "byteman.jar", "from source": "/usr/local/byteman/lib/byteman.jar", "to destination": "/usr/local/byteman/lib/byteman.jar", "output": ""}
2024-07-26T05:34:37.301Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	chaosdaemon/jvm_server.go:87	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "/usr/local/bin/nsexec -m /proc/31861/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman-helper.jar"}
2024-07-26T05:34:37.308Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	copy	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "jar name": "byteman-helper.jar", "from source": "/usr/local/byteman/lib/byteman-helper.jar", "to destination": "/usr/local/byteman/lib/byteman-helper.jar", "output": ""}
2024-07-26T05:34:37.308Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	chaosdaemon/jvm_server.go:87	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "/usr/local/bin/nsexec -m /proc/31861/ns/mnt -- sh -c cat > /usr/local/byteman/lib/chaos-agent.jar"}
2024-07-26T05:34:37.313Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	copy	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "jar name": "chaos-agent.jar", "from source": "/usr/local/byteman/lib/chaos-agent.jar", "to destination": "/usr/local/byteman/lib/chaos-agent.jar", "output": ""}
2024-07-26T05:34:37.313Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4448	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compileToBytecode -p 9288 31861"}
2024-07-26T05:34:38.191Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	exec comamnd	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "cmd": "/bin/sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compileToBytecode -p 9288 31861", "output": "com.sun.tools.attach.AgentLoadException: 0\ncom.sun.tools.attach.AgentLoadException: 0\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)\n\tat jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)\n\tat jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538)\n\tat org.chaos_mesh.agent_installer.Install.injectAgent(Install.java:255)\n\tat org.chaos_mesh.agent_installer.Install.main(Install.java:48)\n", "error": "exit status 1"}
2024-07-26T05:34:38.192Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4448	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "/usr/local/bin/nsexec -n /proc/31861/ns/net -- sh -c bmsubmit.sh -p 9288 -b /usr/local/byteman/lib/byteman-helper.jar"}
2024-07-26T05:34:38.291Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	submit helper jar	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "output": "append boot jar /usr/local/byteman/lib/byteman-helper.jar\n\n"}
2024-07-26T05:34:38.291Z	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	pb/chaosdaemon.pb.go:4448	build command	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "command": "/usr/local/bin/nsexec -n /proc/31861/ns/net -- sh -c bmsubmit.sh -p 9288 -l /tmp/rule.btm2854052829"}
2024-07-26T05:34:38.764Z	INFO	chaos-daemon.daemon-server	chaosdaemon/server.go:187	submit rules	{"namespacedName": "assassin-ser/88rrrrrrrrrrrrrr", "output": "install rule --mysql-1721972077\n\n"}

**Comment by YifanYang6** [comment]
Related: while investigating #4454 (the `null` SQL / NPE issue), we also confirmed a separate fundamental problem with the MySQL chaos action — the Byteman rule's BIND expression reads `$2` from `NativeSession.execSQL`, which is **always null for PreparedStatement execution paths** (the SQL is compiled into the `NativePacketPayload` instead of being passed as a string parameter).

This means even if the classloader issue you reported here is resolved, the MySQL chaos action still won't work for applications using MyBatis, Hibernate, HikariCP, or any other framework that uses `PreparedStatement` — which is virtually every production Java app.

We have a working fix for the null-SQL issue in #4454 — see https://github.com/chaos-mesh/chaos-mesh/issues/4454#issuecomment-4689239292 for the root cause analysis and implementation details. The fix adds a reflection-based `extractSQL()` helper method to [`SQLHelper`](https://github.com/chaos-mesh/byteman-helper/blob/ff5acb4/BytemanHelper/src/main/java/org/chaos_mesh/byteman/helper/SQLHelper.java) that recovers the SQL from `PreparedQuery.getOriginalSql()` when the direct `$2` parameter is null.

The classloader isolation problem you describe here (JBoss/WildFly can't see `org.chaos_mesh.byteman.helper.SQLHelper` from the boot classpath) is a separate issue and would require a different fix — likely related to how `bmsubmit.sh -b` adds the helper JAR and how JBoss's modular classloader interacts with Byteman's helper class resolution.
