### ISSUE TITLE
Experiment details page - Unexpected Application Error - Cannot read properties of undefined (reading 'namespaces')

### ISSUE THREAD

**Issue by gustavoromerobenitez** [chaos-mesh/chaos-mesh#4461]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5-gke.1091002
```

**What version of Chaos Mesh are you using?**
I have confirmed this bug is present on both the **latest** version of the images and Helm chart (as of **31st of July, 2024**) and also on version v2.6.3 as below:

```
Controller manager Version: version.Info{GitVersion:"chart-2.6.3", GitCommit:"b159d1c5a361ca350ca7789c9eb7fc917479db39", BuildDate:"2024-01-23T15:04:53Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do? / Minimal Reproducible Example**

1. Installed Chaos Mesh v2.6.3 via the Helm chart in artifacthub.io
2. Created GCP Credentials secret as per the documentation.
3. Created a GCP Fault -> Node Stop (Tried both via a YAML manifest with kubectl and via the GUI )
4. The experiment appears in the GUI.
5. I click on the experiment name in the GUI. 

**What did you expect to see?**
The details of the experiment.

**What did you see instead?**
The following error appears on an empty browser page. After this, the whole UI is unresponsive, even the left hand menu, until I refresh the page entirely.

```
TypeError: Cannot read properties of undefined (reading 'namespaces')
    at lh (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1687755)
    at na (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1190929)
    at Ws (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1243273)
    at El (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1230519)
    at Cl (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1230447)
    at Sl (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1230310)
    at vl (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1227276)
    at https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1176721
    at t.unstable_runWithPriority (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1290882)
    at Ho (https://chaos-mesh.testing.nonprod.copa.gcp.generali-cloud.com/static/js/main.6ecbba79.js:2:1176498)
```  

**Output of chaosctl**
Not used

**Comment by HillbertChan** [comment]
same error when create an new exp

**Comment by cliffehmm** [comment]
I've been seeing the same issue. From what I can tell from poking around a bit, it's because the dashboard expects all experiments to contain `spec.selector.namespaces`, and the GCP Chaos experiments do not.

You can also see this when trying to "Load From..." an existing GCP Chaos experiment:

<img width="689" alt="Image" src="https://github.com/user-attachments/assets/45af3ac2-dfae-4e3c-8c29-2dc58fb8efa3" />
