### ISSUE TITLE
IOChaos, latency experiment -  toda startup takes too long or an error occurs

### ISSUE THREAD

**Issue by eedjama** [chaos-mesh/chaos-mesh#4550]
### Chaos Mesh Version

v2.7.0

### Kubernetes Version

v1.29.1

### Describe the bug

Running IOChaos in Apache Kafka triggers a container restart.

The restart seems to be triggered by chaosMesh then the toda process running inside of the container reaches 100% CPU utilization and restarts multiple times (was observed every 4-5 sec).
From the logs we see: "rpc error: code = Unknown desc = toda startup takes too long or an error occurs:".

There is no issue if less partitions are configured in the topics.

### To Reproduce

Deploy Apache Kafka and configure 80 topics each with 20 partitions. See example below for topic and partition creation
for (( i=1; i <= 80; ++i )) do /usr/bin/kafka-topics.sh --bootstrap-server=<String: server to connect to> --create --topic topic-$i  --partitions 20; done

Probably this issue can be reproduced with any other product by creating many files in the PV path which IOChaos should apply latency.

**Comment by STRRL** [comment]
That should be a known performance issue, when IOChaos take effects, it would use ptrace to pause the target process, then replace all the fds with chaofs(toda's fuse);And it will do take lots of time to resolve heavy workloads.

I think the "paused" (by ptrace) process missed liveness probe so kubelet kill it.

I have no idea about this for now... maybe start IOChaos experiment before sending heavy workload, or maybe remove liveness probe temporarily.

**Comment by STRRL** [comment]
If you have other ideas about this issue, feel free to share it!

**Comment by eedjama** [comment]
Hi,
thank you for your comment.
We are looking into this and will then update you.

**Comment by doubledna** [comment]
@g1eny0ung @STRRL I encountered the same problem when using version 2.8 to perform IO latency testing. Is there a way to resolve this issue?

**Comment by STRRL** [comment]
> [@g1eny0ung](https://github.com/g1eny0ung) [@STRRL](https://github.com/STRRL) I encountered the same problem when using version 2.8 to perform IO latency testing. Is there a way to resolve this issue?

Could you provide the spec of IOChaos in yaml? It would be very helpful.

**Comment by STRRL** [comment]
Also if you could provide logs of chaos-daemon, which is on the same node with inejected pod

**Comment by STRRL** [comment]
anyway, @g1eny0ung mentions that we could expose a config to let user tune the toda timeout, that would be a way to migitate.

**Comment by STRRL** [comment]
> anyway, [@g1eny0ung](https://github.com/g1eny0ung) mentions that we could expose a config to let user tune the toda timeout, that would be a way to migitate.

@copilot pls take a look and propuse a PR pls

**Comment by STRRL** [comment]
> > anyway, [@g1eny0ung](https://github.com/g1eny0ung) mentions that we could expose a config to let user tune the toda timeout, that would be a way to migitate.
> 
> @copilot pls take a look and propuse a PR pls

@Copilot?

**Comment by doubledna** [comment]
> Also if you could provide logs of chaos-daemon, which is on the same node with inejected pod另外，如果您能提供 chaos-daemon 的日志就更好了，它与被注入的 pod 位于同一节点上。

this is my IOChaos yaml
`
kind: IOChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: milvus-in01-cb5503ad6ec5bc8
  name: io-latency-1
spec:
  selector:
    namespaces:
      - milvus-in01-cb5503ad6ec5bc8
    labelSelectors:
      app.kubernetes.io/component: standalone
  mode: all
  action: latency
  delay: 2000ms
  path: /milvus/data/**/*
  methods:
    - read
    - write
  percent: 100
  volumePath: /milvus/data
  duration: 2m
`

this is log

<img width="1452" height="92" alt="Image" src="https://github.com/user-attachments/assets/a86a26ee-7137-4e09-9685-76999f169d81" />

**Comment by CyanideCentral** [comment]
I encountered this problem when I was trying to inject an IO fault to the postgresQL pod of OpenTelemetry demo (deployed on kind). This is the related logs of chaos-daemon:

```2025-12-31T17:40:34.028Z        INFO    chaos-daemon.daemon-server      chaosdaemon/server.go:187       Waiting for toda to start      {"namespacedName": "otel-demo/postgresql-75649c9dc-tnbpl"}
Dec 31 17:40:34.037  INFO toda: start with option: Options { path: "", mount_only: false, verbose: "info" }
Dec 31 17:40:34.037  INFO inject{injector_config=[]}: toda: inject with config []
Dec 31 17:40:34.037  INFO inject{injector_config=[]}: toda: canonicalizing path
Dec 31 17:40:34.037  INFO toda: waiting for signal to exit
Dec 31 17:40:34.043  INFO toda::jsonrpc: Starting jsonrpc server
Dec 31 17:40:34.043  INFO toda::jsonrpc: Creating jsonrpc server
Dec 31 17:40:34.043  INFO toda::jsonrpc: Creating jsonrpc handler
Dec 31 17:40:34.045  INFO toda::jsonrpc: rpc update called
Dec 31 17:40:34.046  INFO toda::jsonrpc: rpc get_status called
thread '<unnamed>' panicked at 'Send through channel failed: SendError { .. }', src/jsonrpc.rs:74:22
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2025-12-31T17:40:36.029Z        INFO    chaos-daemon.daemon-server      chaosdaemon/server.go:187       Starting toda takes too long or encounter an error      {"namespacedName": "otel-demo/postgresql-75649c9dc-tnbpl"}
Dec 31 17:40:36.029  INFO toda: start to recover and exit```

**Comment by doubledna** [comment]
> I encountered this problem when I was trying to inject an IO fault to the postgresQL pod of OpenTelemetry demo (deployed on kind). This is the related logs of chaos-daemon:我在尝试向 OpenTelemetry demo（部署在 kind 上）的 postgresQL pod 注入 IO 故障时遇到了这个问题。以下是 chaos-daemon 的相关日志：
> 
> ```
> Dec 31 17:40:34.037  INFO toda: start with option: Options { path: "", mount_only: false, verbose: "info" }
> Dec 31 17:40:34.037  INFO inject{injector_config=[]}: toda: inject with config []
> Dec 31 17:40:34.037  INFO inject{injector_config=[]}: toda: canonicalizing path
> Dec 31 17:40:34.037  INFO toda: waiting for signal to exit
> Dec 31 17:40:34.043  INFO toda::jsonrpc: Starting jsonrpc server
> Dec 31 17:40:34.043  INFO toda::jsonrpc: Creating jsonrpc server
> Dec 31 17:40:34.043  INFO toda::jsonrpc: Creating jsonrpc handler
> Dec 31 17:40:34.045  INFO toda::jsonrpc: rpc update called
> Dec 31 17:40:34.046  INFO toda::jsonrpc: rpc get_status called
> thread '<unnamed>' panicked at 'Send through channel failed: SendError { .. }', src/jsonrpc.rs:74:22
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> 2025-12-31T17:40:36.029Z        INFO    chaos-daemon.daemon-server      chaosdaemon/server.go:187       Starting toda takes too long or encounter an error      {"namespacedName": "otel-demo/postgresql-75649c9dc-tnbpl"}
> Dec 31 17:40:36.029  INFO toda: start to recover and exit```
> ```
you can use `kubeclt describe IOChaos xxx -n xxx` to check the chaos record. If the record event is "toda startup takes too long or an error occurs," then you can build an image based on this branch: https://github.com/chaos-mesh/chaos-mesh/tree/copilot/fix-iochaos-latency-issue to resolve this issue. I was able to execute the IO fault correctly using this branch. The official documentation hasn't yet addressed this issue.
