### ISSUE TITLE
dashboard not worked

### ISSUE THREAD

**Issue by leroy-chen** [chaos-mesh/chaos-mesh#802]
## Bug Report

**What version of Kubernetes are you using?**
```kuberctl version```
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-tke.10", GitCommit:"46c858b1d5ab1b0328f9ce62df51b0182852e99d", GitTreeState:"clean", BuildDate:"2019-08-29T07:26:37Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4-tke.10", GitCommit:"46c858b1d5ab1b0328f9ce62df51b0182852e99d", GitTreeState:"clean", BuildDate:"2019-08-29T07:24:21Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
```
git clone https://github.com/chaos-mesh/chaos-mesh.git
cd chaos-mesh/
kubectl apply -f manifests/crd.yaml
kubectl create ns chaos-testing
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set dashboard.create=true
```
**What did you expect to see?**
dashboard work successfully.

**What did you see instead?**
chaos-dashboard seens not worked.
```kubectl get all -n chaos-testing```
```
NAME                                            READY   STATUS             RESTARTS   AGE
pod/chaos-controller-manager-6894cd455d-6g8pr   1/1     Running            0          175m
pod/chaos-daemon-gbxvf                          1/1     Running            0          175m
pod/chaos-daemon-z4qr8                          1/1     Running            0          175m
pod/chaos-dashboard-8969d975c-nkwmp             0/1     CrashLoopBackOff   38         175m

NAME                                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                       AGE
service/chaos-dashboard                 NodePort    9.166.251.120   <none>        2333:32022/TCP                175m
service/chaos-mesh-controller-manager   ClusterIP   9.166.251.4     <none>        10081/TCP,10080/TCP,443/TCP   175m

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/chaos-daemon   2         2         2       2            2           <none>          175m

NAME                                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/chaos-controller-manager   1         1         1            1           175m
deployment.apps/chaos-dashboard            1         1         1            0           175m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/chaos-controller-manager-6894cd455d   1         1         1       175m
replicaset.apps/chaos-dashboard-8969d975c             1         1         0       175m
```

kubectl logs chaos-dashboard-8969d975c-nkwmp -n chaos-testing
```
Chaos Dashboard Version: version.Info{GitVersion:"chart-0.1.0.47+dd4a90a5ebc66e", GitCommit:"dd4a90a5ebc66e35b49dce045941b46315407217", BuildDate:"2020-08-10T06:59:32Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
2020/08/11 06:58:20 [Fx] PROVIDE        <-chan struct {} <= main.main.func1()
2020/08/11 06:58:20 [Fx] PROVIDE        *config.ChaosDashboardConfig <= main.main.func1()
2020/08/11 06:58:20 [Fx] PROVIDE        ttlcontroller.TTLconfig <= main.main.func1()
2020/08/11 06:58:20 [Fx] PROVIDE        *dbstore.DB <= github.com/chaos-mesh/chaos-mesh/pkg/store/dbstore.NewDBStore()
2020/08/11 06:58:20 [Fx] PROVIDE        *collector.Server <= github.com/chaos-mesh/chaos-mesh/pkg/collector.NewServer()
2020/08/11 06:58:20 [Fx] PROVIDE        client.Client <= github.com/chaos-mesh/chaos-mesh/pkg/collector.NewServer()
2020/08/11 06:58:20 [Fx] PROVIDE        *ttlcontroller.Controller <= github.com/chaos-mesh/chaos-mesh/pkg/ttlcontroller.NewController()
2020/08/11 06:58:20 [Fx] PROVIDE        core.EventStore <= github.com/chaos-mesh/chaos-mesh/pkg/store/event.NewStore()
2020/08/11 06:58:20 [Fx] PROVIDE        core.ExperimentStore <= github.com/chaos-mesh/chaos-mesh/pkg/store/experiment.NewStore()
2020/08/11 06:58:20 [Fx] PROVIDE        http.FileSystem <= github.com/chaos-mesh/chaos-mesh/pkg/uiserver.AssetFS()
2020/08/11 06:58:20 [Fx] PROVIDE        *gin.Engine <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newAPIHandlerEngine()
2020/08/11 06:58:20 [Fx] PROVIDE        *gin.RouterGroup <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver.newAPIHandlerEngine()
2020/08/11 06:58:20 [Fx] PROVIDE        *apiserver.Server <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver.NewServer()
2020/08/11 06:58:20 [Fx] PROVIDE        *common.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.NewService()
2020/08/11 06:58:20 [Fx] PROVIDE        *experiment.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.NewService()
2020/08/11 06:58:20 [Fx] PROVIDE        *event.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.NewService()
2020/08/11 06:58:20 [Fx] PROVIDE        *archive.Service <= github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.NewService()
2020/08/11 06:58:20 [Fx] PROVIDE        fx.Lifecycle <= go.uber.org/fx.New.func1()
2020/08/11 06:58:20 [Fx] PROVIDE        fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
2020/08/11 06:58:20 [Fx] PROVIDE        fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver.serverRegister()
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.Register()
2020-08-11T06:58:20.620Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
[GIN-debug] POST   /api/common/pods          --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).listPods-fm (4 handlers)
[GIN-debug] GET    /api/common/namespaces    --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getNamespaces-fm (4 handlers)
[GIN-debug] GET    /api/common/kinds         --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getKinds-fm (4 handlers)
[GIN-debug] GET    /api/common/labels        --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getLabels-fm (4 handlers)
[GIN-debug] GET    /api/common/annotations   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/common.(*Service).getAnnotations-fm (4 handlers)
2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.Register()
[GIN-debug] GET    /api/experiments          --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).listExperiments-fm (4 handlers)
[GIN-debug] POST   /api/experiments/new      --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).createExperiment-fm (4 handlers)
[GIN-debug] GET    /api/experiments/detail/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).getExperimentDetail-fm (4 handlers)
[GIN-debug] DELETE /api/experiments/:uid     --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).deleteExperiment-fm (4 handlers)
[GIN-debug] PUT    /api/experiments/update   --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).updateExperiment-fm (4 handlers)
[GIN-debug] PUT    /api/experiments/pause/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).pauseExperiment-fm (4 handlers)
[GIN-debug] PUT    /api/experiments/start/:uid --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).startExperiment-fm (4 handlers)
[GIN-debug] GET    /api/experiments/state    --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).state-fm (4 handlers)
2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.Register()
[GIN-debug] GET    /api/events               --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.(*Service).listEvents-fm (4 handlers)
[GIN-debug] GET    /api/events/dry           --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/event.(*Service).listDryEvents-fm (4 handlers)
2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.Register()
[GIN-debug] GET    /api/archives             --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).listExperiments-fm (4 handlers)
[GIN-debug] GET    /api/archives/detail/search --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).experimentDetailSearch-fm (4 handlers)
[GIN-debug] GET    /api/archives/detail      --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).experimentDetail-fm (4 handlers)
[GIN-debug] GET    /api/archives/report      --> github.com/chaos-mesh/chaos-mesh/pkg/apiserver/archive.(*Service).experimentReport-fm (4 handlers)
2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/collector.Register()
2020/08/11 06:58:20 [Fx] INVOKE         github.com/chaos-mesh/chaos-mesh/pkg/ttlcontroller.Register()
2020-08-11T06:58:20.621Z        INFO    database ttl controller starting database TTL controller
2020/08/11 06:58:20 [Fx] START          github.com/chaos-mesh/chaos-mesh/pkg/apiserver.serverRegister()
2020/08/11 06:58:20 [Fx] RUNNING
2020-08-11T06:58:20.621Z        INFO    collector       Starting collector
2020-08-11T06:58:20.621Z        INFO    database ttl controller deleting expired data from the database
2020-08-11T06:58:20.621Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
2020-08-11T06:58:20.621Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "podchaos", "source": "kind source: /, Kind="}
2020-08-11T06:58:20.621Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "timechaos", "source": "kind source: /, Kind="}
2020-08-11T06:58:20.622Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "iochaos", "source": "kind source: /, Kind="}
2020-08-11T06:58:20.622Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "networkchaos", "source": "kind source: /, Kind="}
2020-08-11T06:58:20.621Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "kernelchaos", "source": "kind source: /, Kind="}
2020-08-11T06:58:20.623Z        INFO    controller-runtime.controller   Starting EventSource    {"controller": "stresschaos", "source": "kind source: /, Kind="}
2020-08-11T06:58:20.721Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "podchaos"}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting workers        {"controller": "podchaos", "worker count": 1}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "timechaos"}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting workers        {"controller": "timechaos", "worker count": 1}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "iochaos"}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting workers        {"controller": "iochaos", "worker count": 1}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "networkchaos"}
2020-08-11T06:58:20.722Z        INFO    controller-runtime.controller   Starting workers        {"controller": "networkchaos", "worker count": 1}
2020-08-11T06:58:20.724Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "kernelchaos"}
2020-08-11T06:58:20.724Z        INFO    controller-runtime.controller   Starting workers        {"controller": "kernelchaos", "worker count": 1}
2020-08-11T06:58:20.725Z        INFO    controller-runtime.controller   Starting Controller     {"controller": "stresschaos"}
2020-08-11T06:58:20.725Z        INFO    controller-runtime.controller   Starting workers        {"controller": "stresschaos", "worker count": 1}
E0811 06:58:20.739890       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 241 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x188f380, 0x2c4c520)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x188f380, 0x2c4c520)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).updateOrCreateEvent(0xc0006912c0, 0xc0016bf890, 0x7, 0xc0016bf880, 0x5, 0x1752755, 0xb, 0xc0012fe1d8, 0xc00178c3c0, 0x24, ...)
        /src/pkg/collector/collector.go:155 +0xb1
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).recordEvent(0xc0006912c0, 0xc0016bf890, 0x7, 0xc0016bf880, 0x5, 0x1fc7300, 0xc0012fe000, 0x0, 0x0)
        /src/pkg/collector/collector.go:116 +0x1ac
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).Reconcile(0xc0006912c0, 0xc0016bf890, 0x7, 0xc0016bf880, 0x5, 0x0, 0xbfc4ae432b382a35, 0xc000138900, 0xc0001387e8)
        /src/pkg/collector/collector.go:82 +0x44f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006c4900, 0x18f5220, 0xc001741600, 0x414400)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006c4900, 0xc000653600)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0006c4900)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00173b310)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00173b310, 0x3b9aca00, 0x0, 0xc000031e01, 0xc00069d5c0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00173b310, 0x3b9aca00, 0xc00069d5c0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16009e1]

goroutine 241 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x188f380, 0x2c4c520)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).updateOrCreateEvent(0xc0006912c0, 0xc0016bf890, 0x7, 0xc0016bf880, 0x5, 0x1752755, 0xb, 0xc0012fe1d8, 0xc00178c3c0, 0x24, ...)
        /src/pkg/collector/collector.go:155 +0xb1
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).recordEvent(0xc0006912c0, 0xc0016bf890, 0x7, 0xc0016bf880, 0x5, 0x1fc7300, 0xc0012fe000, 0x0, 0x0)
        /src/pkg/collector/collector.go:116 +0x1ac
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).Reconcile(0xc0006912c0, 0xc0016bf890, 0x7, 0xc0016bf880, 0x5, 0x0, 0xbfc4ae432b382a35, 0xc000138900, 0xc0001387e8)
        /src/pkg/collector/collector.go:82 +0x44f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006c4900, 0x18f5220, 0xc001741600, 0x414400)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006c4900, 0xc000653600)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0006c4900)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00173b310)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00173b310, 0x3b9aca00, 0x0, 0xc000031e01, 0xc00069d5c0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00173b310, 0x3b9aca00, 0xc00069d5c0)
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x305 
```

**Comment by fewdan** [comment]
@leroy-chen 
This issue is being processed and will be fixed soon.

**Comment by leroy-chen** [comment]
thanks, btw, How can i rollback to the lastest worked version to continue test?

**Comment by fewdan** [comment]
You can first create an experiment with "kubectl apply -f".

**Comment by fewdan** [comment]
@leroy-chen Can you provide information about the stresschaos you created? 
"kubectl describe StressChaos your-name -n your-namespace"

**Comment by leroy-chen** [comment]
kubectl get StressChaos -n chaos-testing
No resources found.

**Comment by fewdan** [comment]
@leroy-chen What kind of chaos did you create? Can you provide some other information?

**Comment by ClSlaid** [comment]
Have you solved your problem?
I ajusted the script from 
```bash
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set dashboard.create=true
```
to
```bash
helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing --set dashboard.create=true
```
that worked well on my Manjaro Linux.

**Comment by leroy-chen** [comment]
I finally get my dashboard worked.
if someone have the same problem, do check if there are some Chaos failed.
```
kubectl get PodChaos --all-namespaces
kubectl get NetworkChaos --all-namespaces
kubectl get StressChaos --all-namespaces
kubectl get TimeChaos --all-namespaces
kubectl get IoChaos --all-namespaces
kubectl get KernelChaos --all-namespaces
```
then delete the failed chaos .
```
kubectl delete XXChaos chaos-name --force --grace-period=0
```
sometimes you will find it  you can't delete it, try the following script to path.
```
kubectl patch XXChaos chaos-name --type merge -p '{"metadata":{"finalizers":[]}}'
```
